"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.models import workspaceresponse as models_workspaceresponse
from airbyte_api.types import BaseModel, UNSET_SENTINEL
import httpx
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreateWorkspaceResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    workspace_response: NotRequired[models_workspaceresponse.WorkspaceResponseTypedDict]
    r"""Successful operation"""


class CreateWorkspaceResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    workspace_response: Optional[models_workspaceresponse.WorkspaceResponse] = None
    r"""Successful operation"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["WorkspaceResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
