"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel
from airbyte_api.utils import FieldMetadata, PathParamMetadata
import httpx
import pydantic
from typing_extensions import Annotated, TypedDict


class DeleteSourceRequestTypedDict(TypedDict):
    source_id: str


class DeleteSourceRequest(BaseModel):
    source_id: Annotated[
        str,
        pydantic.Field(alias="sourceId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class DeleteSourceResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""


class DeleteSourceResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
