# !NOTE: Speakeasy CLI version 1.508.0 is the last version compatible with the Python v1 
# generator. After upgrading to the Python v2 generator, update `speakeasyVersion` to 
# `latest` to ensure you continue to receive the latest updates.
# 
# See: https://www.speakeasy.com/docs/manage/migrate/python-migration

workflowVersion: 1.0.0
speakeasyVersion: 1.508.0
sources:
    my-source:
        inputs:
            - location: https://raw.githubusercontent.com/airbytehq/airbyte-platform/refs/heads/main/airbyte-api/server-api/src/main/openapi/api_sdk.yaml
        registry:
            location: registry.speakeasyapi.dev/airbyte/airbyte-prod/my-source
targets:
    python-api:
        target: python
        source: my-source
        publish:
            pypi:
                token: $PYPI_TOKEN
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/airbyte/airbyte-prod/my-source-python-code-samples
            blocking: false
