workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://raw.githubusercontent.com/airbytehq/airbyte-platform/refs/heads/main/airbyte-api/server-api/src/main/openapi/api_sdk.yaml
        registry:
            location: registry.speakeasyapi.dev/airbyte/airbyte-prod/my-source
targets:
    python-api:
        target: python
        source: my-source
        publish:
            pypi:
                token: $PYPI_TOKEN
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/airbyte/airbyte-prod/my-source-python-code-samples
            blocking: false
