"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from airbyte import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Final


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class DestinationXata:
    r"""The values required to configure the destination."""
    api_key: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('api_key') }})
    r"""API Key to connect."""
    db_url: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('db_url') }})
    r"""URL pointing to your workspace."""
    DESTINATION_TYPE: Final[str] = dataclasses.field(default='xata', metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('destinationType') }})
    

