"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from airbyte import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Any

class DestinationDevNullDevNull(str, Enum):
    DEV_NULL = 'dev-null'

class DestinationDevNullTestDestinationSilentTestDestinationType(str, Enum):
    SILENT = 'SILENT'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class DestinationDevNullTestDestinationSilent:
    r"""The type of destination to be used"""
    test_destination_type: DestinationDevNullTestDestinationSilentTestDestinationType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('test_destination_type') }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class DestinationDevNull:
    r"""The values required to configure the destination."""
    destination_type: DestinationDevNullDevNull = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('destinationType') }})
    test_destination: Any = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('test_destination') }})
    r"""The type of destination to be used"""
    

