"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel, UNSET_SENTINEL
from airbyte_api.utils import validate_const
from enum import Enum
import pydantic
from pydantic import ConfigDict, model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Any, Dict, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class Clickhouse(str, Enum):
    CLICKHOUSE = "clickhouse"


class Protocol(str, Enum):
    r"""Protocol for the database connection string."""

    HTTP = "http"
    HTTPS = "https"


class DestinationClickhouseSchemasTunnelMethod(str, Enum):
    SSH_PASSWORD_AUTH = "SSH_PASSWORD_AUTH"


class PasswordAuthenticationTypedDict(TypedDict):
    r"""Connect through a jump server tunnel host using username and password authentication"""

    tunnel_host: str
    r"""Hostname of the jump server host that allows inbound ssh tunnel."""
    tunnel_user: str
    r"""OS-level username for logging into the jump server host"""
    tunnel_user_password: str
    r"""OS-level password for logging into the jump server host"""
    tunnel_method: NotRequired[DestinationClickhouseSchemasTunnelMethod]
    tunnel_port: NotRequired[int]
    r"""Port on the proxy/jump server that accepts inbound ssh connections."""


class PasswordAuthentication(BaseModel):
    r"""Connect through a jump server tunnel host using username and password authentication"""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    tunnel_host: str
    r"""Hostname of the jump server host that allows inbound ssh tunnel."""

    tunnel_user: str
    r"""OS-level username for logging into the jump server host"""

    tunnel_user_password: str
    r"""OS-level password for logging into the jump server host"""

    tunnel_method: Optional[DestinationClickhouseSchemasTunnelMethod] = (
        DestinationClickhouseSchemasTunnelMethod.SSH_PASSWORD_AUTH
    )

    tunnel_port: Optional[int] = 22
    r"""Port on the proxy/jump server that accepts inbound ssh connections."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["tunnel_method", "tunnel_port"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            serialized.pop(k, serialized.pop(n, None))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m


class DestinationClickhouseTunnelMethod(str, Enum):
    SSH_KEY_AUTH = "SSH_KEY_AUTH"


class SSHKeyAuthenticationTypedDict(TypedDict):
    r"""Connect through a jump server tunnel host using username and ssh key"""

    ssh_key: str
    r"""OS-level user account ssh key credentials in RSA PEM format ( created with ssh-keygen -t rsa -m PEM -f myuser_rsa )"""
    tunnel_host: str
    r"""Hostname of the jump server host that allows inbound ssh tunnel."""
    tunnel_user: str
    r"""OS-level username for logging into the jump server host"""
    tunnel_method: NotRequired[DestinationClickhouseTunnelMethod]
    tunnel_port: NotRequired[int]
    r"""Port on the proxy/jump server that accepts inbound ssh connections."""


class SSHKeyAuthentication(BaseModel):
    r"""Connect through a jump server tunnel host using username and ssh key"""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    ssh_key: str
    r"""OS-level user account ssh key credentials in RSA PEM format ( created with ssh-keygen -t rsa -m PEM -f myuser_rsa )"""

    tunnel_host: str
    r"""Hostname of the jump server host that allows inbound ssh tunnel."""

    tunnel_user: str
    r"""OS-level username for logging into the jump server host"""

    tunnel_method: Optional[DestinationClickhouseTunnelMethod] = (
        DestinationClickhouseTunnelMethod.SSH_KEY_AUTH
    )

    tunnel_port: Optional[int] = 22
    r"""Port on the proxy/jump server that accepts inbound ssh connections."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["tunnel_method", "tunnel_port"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            serialized.pop(k, serialized.pop(n, None))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m


class TunnelMethod(str, Enum):
    NO_TUNNEL = "NO_TUNNEL"


class NoTunnelTypedDict(TypedDict):
    r"""No ssh tunnel needed to connect to database"""

    tunnel_method: NotRequired[TunnelMethod]


class NoTunnel(BaseModel):
    r"""No ssh tunnel needed to connect to database"""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    tunnel_method: Optional[TunnelMethod] = TunnelMethod.NO_TUNNEL

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["tunnel_method"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            serialized.pop(k, serialized.pop(n, None))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m


SSHTunnelMethodTypedDict = TypeAliasType(
    "SSHTunnelMethodTypedDict",
    Union[
        NoTunnelTypedDict,
        SSHKeyAuthenticationTypedDict,
        PasswordAuthenticationTypedDict,
    ],
)
r"""Whether to initiate an SSH tunnel before connecting to the database, and if so, which kind of authentication to use."""


SSHTunnelMethod = TypeAliasType(
    "SSHTunnelMethod", Union[NoTunnel, SSHKeyAuthentication, PasswordAuthentication]
)
r"""Whether to initiate an SSH tunnel before connecting to the database, and if so, which kind of authentication to use."""


class DestinationClickhouseTypedDict(TypedDict):
    host: str
    r"""Hostname of the database."""
    password: str
    r"""Password associated with the username."""
    database: NotRequired[str]
    r"""Name of the database."""
    destination_type: Clickhouse
    enable_json: NotRequired[bool]
    r"""Use the JSON type for Object fields. If disabled, the JSON will be converted to a string."""
    port: NotRequired[str]
    r"""HTTP port of the database. Default(s) HTTP: 8123 — HTTPS: 8443"""
    protocol: NotRequired[Protocol]
    r"""Protocol for the database connection string."""
    record_window_size: NotRequired[int]
    r"""Warning: Tuning this parameter can impact the performances. The maximum number of records that should be written to a batch. The batch size limit is still limited to 70 Mb"""
    tunnel_method: NotRequired[SSHTunnelMethodTypedDict]
    r"""Whether to initiate an SSH tunnel before connecting to the database, and if so, which kind of authentication to use."""
    username: NotRequired[str]
    r"""Username to use to access the database."""


class DestinationClickhouse(BaseModel):
    host: str
    r"""Hostname of the database."""

    password: str
    r"""Password associated with the username."""

    database: Optional[str] = "default"
    r"""Name of the database."""

    DESTINATION_TYPE: Annotated[
        Annotated[Clickhouse, AfterValidator(validate_const(Clickhouse.CLICKHOUSE))],
        pydantic.Field(alias="destinationType"),
    ] = Clickhouse.CLICKHOUSE

    enable_json: Optional[bool] = False
    r"""Use the JSON type for Object fields. If disabled, the JSON will be converted to a string."""

    port: Optional[str] = "8443"
    r"""HTTP port of the database. Default(s) HTTP: 8123 — HTTPS: 8443"""

    protocol: Optional[Protocol] = Protocol.HTTPS
    r"""Protocol for the database connection string."""

    record_window_size: Optional[int] = None
    r"""Warning: Tuning this parameter can impact the performances. The maximum number of records that should be written to a batch. The batch size limit is still limited to 70 Mb"""

    tunnel_method: Optional[SSHTunnelMethod] = None
    r"""Whether to initiate an SSH tunnel before connecting to the database, and if so, which kind of authentication to use."""

    username: Optional[str] = "default"
    r"""Username to use to access the database."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "database",
                "enable_json",
                "port",
                "protocol",
                "record_window_size",
                "tunnel_method",
                "username",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    DestinationClickhouse.model_rebuild()
except NameError:
    pass
