"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel, UNSET_SENTINEL
from airbyte_api.utils import validate_const
from enum import Enum
import pydantic
from pydantic import ConfigDict, model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Any, Dict, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class DestinationS3DataLakeCatalogTypeCatalogTypeCatalogType(str, Enum):
    POLARIS = "POLARIS"


class PolarisCatalogTypedDict(TypedDict):
    r"""Configuration details for connecting to an Apache Polaris-based Iceberg catalog."""

    catalog_name: str
    r"""The name of the catalog in Polaris. This corresponds to the catalog name created via the Polaris Management API."""
    client_id: str
    r"""The OAuth Client ID for authenticating with the Polaris server."""
    client_secret: str
    r"""The OAuth Client Secret for authenticating with the Polaris server."""
    namespace: str
    r"""The Polaris namespace to be used in the Table identifier.
    This will ONLY be used if the `Destination Namespace` setting for the connection is set to
    `Destination-defined` or `Source-defined`
    """
    server_uri: str
    r"""The base URL of the Polaris server used to connect to the Polaris catalog."""
    catalog_type: NotRequired[DestinationS3DataLakeCatalogTypeCatalogTypeCatalogType]


class PolarisCatalog(BaseModel):
    r"""Configuration details for connecting to an Apache Polaris-based Iceberg catalog."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    catalog_name: str
    r"""The name of the catalog in Polaris. This corresponds to the catalog name created via the Polaris Management API."""

    client_id: str
    r"""The OAuth Client ID for authenticating with the Polaris server."""

    client_secret: str
    r"""The OAuth Client Secret for authenticating with the Polaris server."""

    namespace: str
    r"""The Polaris namespace to be used in the Table identifier.
    This will ONLY be used if the `Destination Namespace` setting for the connection is set to
    `Destination-defined` or `Source-defined`
    """

    server_uri: str
    r"""The base URL of the Polaris server used to connect to the Polaris catalog."""

    catalog_type: Optional[DestinationS3DataLakeCatalogTypeCatalogTypeCatalogType] = (
        DestinationS3DataLakeCatalogTypeCatalogTypeCatalogType.POLARIS
    )

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["catalog_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            serialized.pop(k, serialized.pop(n, None))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m


class DestinationS3DataLakeCatalogTypeCatalogType(str, Enum):
    REST = "REST"


class RestCatalogTypedDict(TypedDict):
    r"""Configuration details for connecting to a REST catalog."""

    namespace: str
    r"""The namespace to be used in the Table identifier.
    This will ONLY be used if the `Destination Namespace` setting for the connection is set to
    `Destination-defined` or `Source-defined`
    """
    server_uri: str
    r"""The base URL of the Rest server used to connect to the Rest catalog."""
    catalog_type: NotRequired[DestinationS3DataLakeCatalogTypeCatalogType]


class RestCatalog(BaseModel):
    r"""Configuration details for connecting to a REST catalog."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    namespace: str
    r"""The namespace to be used in the Table identifier.
    This will ONLY be used if the `Destination Namespace` setting for the connection is set to
    `Destination-defined` or `Source-defined`
    """

    server_uri: str
    r"""The base URL of the Rest server used to connect to the Rest catalog."""

    catalog_type: Optional[DestinationS3DataLakeCatalogTypeCatalogType] = (
        DestinationS3DataLakeCatalogTypeCatalogType.REST
    )

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["catalog_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            serialized.pop(k, serialized.pop(n, None))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m


class CatalogTypeCatalogType(str, Enum):
    GLUE = "GLUE"


class GlueCatalogTypedDict(TypedDict):
    r"""Configuration details for connecting to an AWS Glue-based Iceberg catalog."""

    database_name: str
    r"""The Glue database name. This will ONLY be used if the `Destination Namespace` setting for the connection is set to `Destination-defined` or `Source-defined`"""
    glue_id: str
    r"""The AWS Account ID associated with the Glue service used by the Iceberg catalog."""
    catalog_type: NotRequired[CatalogTypeCatalogType]
    role_arn: NotRequired[str]
    r"""The ARN of the AWS role to assume. Only usable in Airbyte Cloud."""


class GlueCatalog(BaseModel):
    r"""Configuration details for connecting to an AWS Glue-based Iceberg catalog."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    database_name: str
    r"""The Glue database name. This will ONLY be used if the `Destination Namespace` setting for the connection is set to `Destination-defined` or `Source-defined`"""

    glue_id: str
    r"""The AWS Account ID associated with the Glue service used by the Iceberg catalog."""

    catalog_type: Optional[CatalogTypeCatalogType] = CatalogTypeCatalogType.GLUE

    role_arn: Optional[str] = None
    r"""The ARN of the AWS role to assume. Only usable in Airbyte Cloud."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["catalog_type", "role_arn"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            serialized.pop(k, serialized.pop(n, None))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m


class DestinationS3DataLakeCatalogTypeCatalogType1CatalogType(str, Enum):
    NESSIE = "NESSIE"


class NessieCatalogTypedDict(TypedDict):
    r"""Configuration details for connecting to a Nessie-based Iceberg catalog."""

    namespace: str
    r"""The Nessie namespace to be used in the Table identifier.
    This will ONLY be used if the `Destination Namespace` setting for the connection is set to
    `Destination-defined` or `Source-defined`
    """
    server_uri: str
    r"""The base URL of the Nessie server used to connect to the Nessie catalog."""
    access_token: NotRequired[str]
    r"""Optional token for authentication with the Nessie server."""
    catalog_type: NotRequired[DestinationS3DataLakeCatalogTypeCatalogType1CatalogType]


class NessieCatalog(BaseModel):
    r"""Configuration details for connecting to a Nessie-based Iceberg catalog."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    namespace: str
    r"""The Nessie namespace to be used in the Table identifier.
    This will ONLY be used if the `Destination Namespace` setting for the connection is set to
    `Destination-defined` or `Source-defined`
    """

    server_uri: str
    r"""The base URL of the Nessie server used to connect to the Nessie catalog."""

    access_token: Optional[str] = None
    r"""Optional token for authentication with the Nessie server."""

    catalog_type: Optional[DestinationS3DataLakeCatalogTypeCatalogType1CatalogType] = (
        DestinationS3DataLakeCatalogTypeCatalogType1CatalogType.NESSIE
    )

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["access_token", "catalog_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            serialized.pop(k, serialized.pop(n, None))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m


CatalogTypeTypedDict = TypeAliasType(
    "CatalogTypeTypedDict",
    Union[
        RestCatalogTypedDict,
        NessieCatalogTypedDict,
        GlueCatalogTypedDict,
        PolarisCatalogTypedDict,
    ],
)
r"""Specifies the type of Iceberg catalog (e.g., NESSIE, GLUE, REST, POLARIS) and its associated configuration."""


CatalogType = TypeAliasType(
    "CatalogType", Union[RestCatalog, NessieCatalog, GlueCatalog, PolarisCatalog]
)
r"""Specifies the type of Iceberg catalog (e.g., NESSIE, GLUE, REST, POLARIS) and its associated configuration."""


class S3DataLake(str, Enum):
    S3_DATA_LAKE = "s3-data-lake"


class DestinationS3DataLakeS3BucketRegion(str, Enum):
    r"""The region of the S3 bucket. See <a href=\"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions\">here</a> for all region codes."""

    UNKNOWN = ""
    AF_SOUTH_1 = "af-south-1"
    AP_EAST_1 = "ap-east-1"
    AP_NORTHEAST_1 = "ap-northeast-1"
    AP_NORTHEAST_2 = "ap-northeast-2"
    AP_NORTHEAST_3 = "ap-northeast-3"
    AP_SOUTH_1 = "ap-south-1"
    AP_SOUTH_2 = "ap-south-2"
    AP_SOUTHEAST_1 = "ap-southeast-1"
    AP_SOUTHEAST_2 = "ap-southeast-2"
    AP_SOUTHEAST_3 = "ap-southeast-3"
    AP_SOUTHEAST_4 = "ap-southeast-4"
    CA_CENTRAL_1 = "ca-central-1"
    CA_WEST_1 = "ca-west-1"
    CN_NORTH_1 = "cn-north-1"
    CN_NORTHWEST_1 = "cn-northwest-1"
    EU_CENTRAL_1 = "eu-central-1"
    EU_CENTRAL_2 = "eu-central-2"
    EU_NORTH_1 = "eu-north-1"
    EU_SOUTH_1 = "eu-south-1"
    EU_SOUTH_2 = "eu-south-2"
    EU_WEST_1 = "eu-west-1"
    EU_WEST_2 = "eu-west-2"
    EU_WEST_3 = "eu-west-3"
    IL_CENTRAL_1 = "il-central-1"
    ME_CENTRAL_1 = "me-central-1"
    ME_SOUTH_1 = "me-south-1"
    SA_EAST_1 = "sa-east-1"
    US_EAST_1 = "us-east-1"
    US_EAST_2 = "us-east-2"
    US_GOV_EAST_1 = "us-gov-east-1"
    US_GOV_WEST_1 = "us-gov-west-1"
    US_WEST_1 = "us-west-1"
    US_WEST_2 = "us-west-2"


class DestinationS3DataLakeTypedDict(TypedDict):
    r"""Defines the configurations required to connect to an Iceberg catalog, including warehouse location, main branch name, and catalog type specifics."""

    catalog_type: CatalogTypeTypedDict
    r"""Specifies the type of Iceberg catalog (e.g., NESSIE, GLUE, REST, POLARIS) and its associated configuration."""
    s3_bucket_name: str
    r"""The name of the S3 bucket that will host the Iceberg data."""
    s3_bucket_region: DestinationS3DataLakeS3BucketRegion
    r"""The region of the S3 bucket. See <a href=\"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions\">here</a> for all region codes."""
    warehouse_location: str
    r"""The root location of the data warehouse used by the Iceberg catalog. Typically includes a bucket name and path within that bucket. For AWS Glue and Nessie, must include the storage protocol (such as \"s3://\" for Amazon S3)."""
    access_key_id: NotRequired[str]
    r"""The AWS Access Key ID with permissions for S3 and Glue operations."""
    destination_type: S3DataLake
    main_branch_name: NotRequired[str]
    r"""The primary or default branch name in the catalog. Most query engines will use \"main\" by default. See <a href=\"https://iceberg.apache.org/docs/latest/branching/\">Iceberg documentation</a> for more information."""
    s3_endpoint: NotRequired[str]
    r"""Your S3 endpoint url. Read more <a href=\"https://docs.aws.amazon.com/general/latest/gr/s3.html#:~:text=Service%20endpoints-,Amazon%20S3%20endpoints,-When%20you%20use\">here</a>"""
    secret_access_key: NotRequired[str]
    r"""The AWS Secret Access Key paired with the Access Key ID for AWS authentication."""


class DestinationS3DataLake(BaseModel):
    r"""Defines the configurations required to connect to an Iceberg catalog, including warehouse location, main branch name, and catalog type specifics."""

    catalog_type: CatalogType
    r"""Specifies the type of Iceberg catalog (e.g., NESSIE, GLUE, REST, POLARIS) and its associated configuration."""

    s3_bucket_name: str
    r"""The name of the S3 bucket that will host the Iceberg data."""

    s3_bucket_region: DestinationS3DataLakeS3BucketRegion
    r"""The region of the S3 bucket. See <a href=\"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions\">here</a> for all region codes."""

    warehouse_location: str
    r"""The root location of the data warehouse used by the Iceberg catalog. Typically includes a bucket name and path within that bucket. For AWS Glue and Nessie, must include the storage protocol (such as \"s3://\" for Amazon S3)."""

    access_key_id: Optional[str] = None
    r"""The AWS Access Key ID with permissions for S3 and Glue operations."""

    DESTINATION_TYPE: Annotated[
        Annotated[S3DataLake, AfterValidator(validate_const(S3DataLake.S3_DATA_LAKE))],
        pydantic.Field(alias="destinationType"),
    ] = S3DataLake.S3_DATA_LAKE

    main_branch_name: Optional[str] = "main"
    r"""The primary or default branch name in the catalog. Most query engines will use \"main\" by default. See <a href=\"https://iceberg.apache.org/docs/latest/branching/\">Iceberg documentation</a> for more information."""

    s3_endpoint: Optional[str] = None
    r"""Your S3 endpoint url. Read more <a href=\"https://docs.aws.amazon.com/general/latest/gr/s3.html#:~:text=Service%20endpoints-,Amazon%20S3%20endpoints,-When%20you%20use\">here</a>"""

    secret_access_key: Optional[str] = None
    r"""The AWS Secret Access Key paired with the Access Key ID for AWS authentication."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["access_key_id", "main_branch_name", "s3_endpoint", "secret_access_key"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    DestinationS3DataLake.model_rebuild()
except NameError:
    pass
