"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel, UNSET_SENTINEL
from airbyte_api.utils import validate_const
from enum import Enum
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Optional, Union
from typing_extensions import (
    Annotated,
    NotRequired,
    TypeAliasType,
    TypedDict,
    deprecated,
)


class Pinecone(str, Enum):
    PINECONE = "pinecone"


class DestinationPineconeModeOpenaiCompatible(str, Enum):
    OPENAI_COMPATIBLE = "openai_compatible"


class DestinationPineconeOpenAICompatibleTypedDict(TypedDict):
    r"""Use a service that's compatible with the OpenAI API to embed text."""

    base_url: str
    r"""The base URL for your OpenAI-compatible service"""
    dimensions: int
    r"""The number of dimensions the embedding model is generating"""
    api_key: NotRequired[str]
    mode: DestinationPineconeModeOpenaiCompatible
    model_name: NotRequired[str]
    r"""The name of the model to use for embedding"""


class DestinationPineconeOpenAICompatible(BaseModel):
    r"""Use a service that's compatible with the OpenAI API to embed text."""

    base_url: str
    r"""The base URL for your OpenAI-compatible service"""

    dimensions: int
    r"""The number of dimensions the embedding model is generating"""

    api_key: Optional[str] = ""

    MODE: Annotated[
        Annotated[
            Optional[DestinationPineconeModeOpenaiCompatible],
            AfterValidator(
                validate_const(
                    DestinationPineconeModeOpenaiCompatible.OPENAI_COMPATIBLE
                )
            ),
        ],
        pydantic.Field(alias="mode"),
    ] = DestinationPineconeModeOpenaiCompatible.OPENAI_COMPATIBLE

    model_name: Optional[str] = "text-embedding-ada-002"
    r"""The name of the model to use for embedding"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["api_key", "mode", "model_name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DestinationPineconeModeAzureOpenai(str, Enum):
    AZURE_OPENAI = "azure_openai"


class DestinationPineconeAzureOpenAITypedDict(TypedDict):
    r"""Use the Azure-hosted OpenAI API to embed text. This option is using the text-embedding-ada-002 model with 1536 embedding dimensions."""

    api_base: str
    r"""The base URL for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource"""
    deployment: str
    r"""The deployment for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource"""
    openai_key: str
    r"""The API key for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource"""
    mode: DestinationPineconeModeAzureOpenai


class DestinationPineconeAzureOpenAI(BaseModel):
    r"""Use the Azure-hosted OpenAI API to embed text. This option is using the text-embedding-ada-002 model with 1536 embedding dimensions."""

    api_base: str
    r"""The base URL for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource"""

    deployment: str
    r"""The deployment for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource"""

    openai_key: str
    r"""The API key for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource"""

    MODE: Annotated[
        Annotated[
            Optional[DestinationPineconeModeAzureOpenai],
            AfterValidator(
                validate_const(DestinationPineconeModeAzureOpenai.AZURE_OPENAI)
            ),
        ],
        pydantic.Field(alias="mode"),
    ] = DestinationPineconeModeAzureOpenai.AZURE_OPENAI

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mode"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DestinationPineconeModeFake(str, Enum):
    FAKE = "fake"


class DestinationPineconeFakeTypedDict(TypedDict):
    r"""Use a fake embedding made out of random vectors with 1536 embedding dimensions. This is useful for testing the data pipeline without incurring any costs."""

    mode: DestinationPineconeModeFake


class DestinationPineconeFake(BaseModel):
    r"""Use a fake embedding made out of random vectors with 1536 embedding dimensions. This is useful for testing the data pipeline without incurring any costs."""

    MODE: Annotated[
        Annotated[
            Optional[DestinationPineconeModeFake],
            AfterValidator(validate_const(DestinationPineconeModeFake.FAKE)),
        ],
        pydantic.Field(alias="mode"),
    ] = DestinationPineconeModeFake.FAKE

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mode"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DestinationPineconeModeCohere(str, Enum):
    COHERE = "cohere"


class DestinationPineconeCohereTypedDict(TypedDict):
    r"""Use the Cohere API to embed text."""

    cohere_key: str
    mode: DestinationPineconeModeCohere


class DestinationPineconeCohere(BaseModel):
    r"""Use the Cohere API to embed text."""

    cohere_key: str

    MODE: Annotated[
        Annotated[
            Optional[DestinationPineconeModeCohere],
            AfterValidator(validate_const(DestinationPineconeModeCohere.COHERE)),
        ],
        pydantic.Field(alias="mode"),
    ] = DestinationPineconeModeCohere.COHERE

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mode"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DestinationPineconeModeOpenai(str, Enum):
    OPENAI = "openai"


class DestinationPineconeOpenAITypedDict(TypedDict):
    r"""Use the OpenAI API to embed text. This option is using the text-embedding-ada-002 model with 1536 embedding dimensions."""

    openai_key: str
    mode: DestinationPineconeModeOpenai


class DestinationPineconeOpenAI(BaseModel):
    r"""Use the OpenAI API to embed text. This option is using the text-embedding-ada-002 model with 1536 embedding dimensions."""

    openai_key: str

    MODE: Annotated[
        Annotated[
            Optional[DestinationPineconeModeOpenai],
            AfterValidator(validate_const(DestinationPineconeModeOpenai.OPENAI)),
        ],
        pydantic.Field(alias="mode"),
    ] = DestinationPineconeModeOpenai.OPENAI

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mode"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


DestinationPineconeEmbeddingTypedDict = TypeAliasType(
    "DestinationPineconeEmbeddingTypedDict",
    Union[
        DestinationPineconeFakeTypedDict,
        DestinationPineconeOpenAITypedDict,
        DestinationPineconeCohereTypedDict,
        DestinationPineconeAzureOpenAITypedDict,
        DestinationPineconeOpenAICompatibleTypedDict,
    ],
)
r"""Embedding configuration"""


DestinationPineconeEmbedding = TypeAliasType(
    "DestinationPineconeEmbedding",
    Union[
        DestinationPineconeFake,
        DestinationPineconeOpenAI,
        DestinationPineconeCohere,
        DestinationPineconeAzureOpenAI,
        DestinationPineconeOpenAICompatible,
    ],
)
r"""Embedding configuration"""


class DestinationPineconeIndexingTypedDict(TypedDict):
    r"""Pinecone is a popular vector store that can be used to store and retrieve embeddings."""

    index: str
    r"""Pinecone index in your project to load data into"""
    pinecone_environment: str
    r"""Pinecone Cloud environment to use"""
    pinecone_key: str
    r"""The Pinecone API key to use matching the environment (copy from Pinecone console)"""


class DestinationPineconeIndexing(BaseModel):
    r"""Pinecone is a popular vector store that can be used to store and retrieve embeddings."""

    index: str
    r"""Pinecone index in your project to load data into"""

    pinecone_environment: str
    r"""Pinecone Cloud environment to use"""

    pinecone_key: str
    r"""The Pinecone API key to use matching the environment (copy from Pinecone console)"""


class DestinationPineconeFieldNameMappingConfigModelTypedDict(TypedDict):
    from_field: str
    r"""The field name in the source"""
    to_field: str
    r"""The field name to use in the destination"""


class DestinationPineconeFieldNameMappingConfigModel(BaseModel):
    from_field: str
    r"""The field name in the source"""

    to_field: str
    r"""The field name to use in the destination"""


class DestinationPineconeLanguage(str, Enum):
    r"""Split code in suitable places based on the programming language"""

    CPP = "cpp"
    GO = "go"
    JAVA = "java"
    JS = "js"
    PHP = "php"
    PROTO = "proto"
    PYTHON = "python"
    RST = "rst"
    RUBY = "ruby"
    RUST = "rust"
    SCALA = "scala"
    SWIFT = "swift"
    MARKDOWN = "markdown"
    LATEX = "latex"
    HTML = "html"
    SOL = "sol"


class DestinationPineconeModeCode(str, Enum):
    CODE = "code"


class DestinationPineconeByProgrammingLanguageTypedDict(TypedDict):
    r"""Split the text by suitable delimiters based on the programming language. This is useful for splitting code into chunks."""

    language: DestinationPineconeLanguage
    r"""Split code in suitable places based on the programming language"""
    mode: DestinationPineconeModeCode


class DestinationPineconeByProgrammingLanguage(BaseModel):
    r"""Split the text by suitable delimiters based on the programming language. This is useful for splitting code into chunks."""

    language: DestinationPineconeLanguage
    r"""Split code in suitable places based on the programming language"""

    MODE: Annotated[
        Annotated[
            Optional[DestinationPineconeModeCode],
            AfterValidator(validate_const(DestinationPineconeModeCode.CODE)),
        ],
        pydantic.Field(alias="mode"),
    ] = DestinationPineconeModeCode.CODE

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mode"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DestinationPineconeModeMarkdown(str, Enum):
    MARKDOWN = "markdown"


class DestinationPineconeByMarkdownHeaderTypedDict(TypedDict):
    r"""Split the text by Markdown headers down to the specified header level. If the chunk size fits multiple sections, they will be combined into a single chunk."""

    mode: DestinationPineconeModeMarkdown
    split_level: NotRequired[int]
    r"""Level of markdown headers to split text fields by. Headings down to the specified level will be used as split points"""


class DestinationPineconeByMarkdownHeader(BaseModel):
    r"""Split the text by Markdown headers down to the specified header level. If the chunk size fits multiple sections, they will be combined into a single chunk."""

    MODE: Annotated[
        Annotated[
            Optional[DestinationPineconeModeMarkdown],
            AfterValidator(validate_const(DestinationPineconeModeMarkdown.MARKDOWN)),
        ],
        pydantic.Field(alias="mode"),
    ] = DestinationPineconeModeMarkdown.MARKDOWN

    split_level: Optional[int] = 1
    r"""Level of markdown headers to split text fields by. Headings down to the specified level will be used as split points"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mode", "split_level"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DestinationPineconeModeSeparator(str, Enum):
    SEPARATOR = "separator"


class DestinationPineconeBySeparatorTypedDict(TypedDict):
    r"""Split the text by the list of separators until the chunk size is reached, using the earlier mentioned separators where possible. This is useful for splitting text fields by paragraphs, sentences, words, etc."""

    keep_separator: NotRequired[bool]
    r"""Whether to keep the separator in the resulting chunks"""
    mode: DestinationPineconeModeSeparator
    separators: NotRequired[List[str]]
    r"""List of separator strings to split text fields by. The separator itself needs to be wrapped in double quotes, e.g. to split by the dot character, use \".\". To split by a newline, use \"\n\"."""


class DestinationPineconeBySeparator(BaseModel):
    r"""Split the text by the list of separators until the chunk size is reached, using the earlier mentioned separators where possible. This is useful for splitting text fields by paragraphs, sentences, words, etc."""

    keep_separator: Optional[bool] = False
    r"""Whether to keep the separator in the resulting chunks"""

    MODE: Annotated[
        Annotated[
            Optional[DestinationPineconeModeSeparator],
            AfterValidator(validate_const(DestinationPineconeModeSeparator.SEPARATOR)),
        ],
        pydantic.Field(alias="mode"),
    ] = DestinationPineconeModeSeparator.SEPARATOR

    separators: Optional[List[str]] = None
    r"""List of separator strings to split text fields by. The separator itself needs to be wrapped in double quotes, e.g. to split by the dot character, use \".\". To split by a newline, use \"\n\"."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["keep_separator", "mode", "separators"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


DestinationPineconeTextSplitterTypedDict = TypeAliasType(
    "DestinationPineconeTextSplitterTypedDict",
    Union[
        DestinationPineconeByMarkdownHeaderTypedDict,
        DestinationPineconeByProgrammingLanguageTypedDict,
        DestinationPineconeBySeparatorTypedDict,
    ],
)
r"""Split text fields into chunks based on the specified method."""


DestinationPineconeTextSplitter = TypeAliasType(
    "DestinationPineconeTextSplitter",
    Union[
        DestinationPineconeByMarkdownHeader,
        DestinationPineconeByProgrammingLanguage,
        DestinationPineconeBySeparator,
    ],
)
r"""Split text fields into chunks based on the specified method."""


class DestinationPineconeProcessingConfigModelTypedDict(TypedDict):
    chunk_size: int
    r"""Size of chunks in tokens to store in vector store (make sure it is not too big for the context if your LLM)"""
    chunk_overlap: NotRequired[int]
    r"""Size of overlap between chunks in tokens to store in vector store to better capture relevant context"""
    field_name_mappings: NotRequired[
        List[DestinationPineconeFieldNameMappingConfigModelTypedDict]
    ]
    r"""List of fields to rename. Not applicable for nested fields, but can be used to rename fields already flattened via dot notation."""
    metadata_fields: NotRequired[List[str]]
    r"""List of fields in the record that should be stored as metadata. The field list is applied to all streams in the same way and non-existing fields are ignored. If none are defined, all fields are considered metadata fields. When specifying text fields, you can access nested fields in the record by using dot notation, e.g. `user.name` will access the `name` field in the `user` object. It's also possible to use wildcards to access all fields in an object, e.g. `users.*.name` will access all `names` fields in all entries of the `users` array. When specifying nested paths, all matching values are flattened into an array set to a field named by the path."""
    text_fields: NotRequired[List[str]]
    r"""List of fields in the record that should be used to calculate the embedding. The field list is applied to all streams in the same way and non-existing fields are ignored. If none are defined, all fields are considered text fields. When specifying text fields, you can access nested fields in the record by using dot notation, e.g. `user.name` will access the `name` field in the `user` object. It's also possible to use wildcards to access all fields in an object, e.g. `users.*.name` will access all `names` fields in all entries of the `users` array."""
    text_splitter: NotRequired[DestinationPineconeTextSplitterTypedDict]
    r"""Split text fields into chunks based on the specified method."""


class DestinationPineconeProcessingConfigModel(BaseModel):
    chunk_size: int
    r"""Size of chunks in tokens to store in vector store (make sure it is not too big for the context if your LLM)"""

    chunk_overlap: Optional[int] = 0
    r"""Size of overlap between chunks in tokens to store in vector store to better capture relevant context"""

    field_name_mappings: Optional[
        List[DestinationPineconeFieldNameMappingConfigModel]
    ] = None
    r"""List of fields to rename. Not applicable for nested fields, but can be used to rename fields already flattened via dot notation."""

    metadata_fields: Optional[List[str]] = None
    r"""List of fields in the record that should be stored as metadata. The field list is applied to all streams in the same way and non-existing fields are ignored. If none are defined, all fields are considered metadata fields. When specifying text fields, you can access nested fields in the record by using dot notation, e.g. `user.name` will access the `name` field in the `user` object. It's also possible to use wildcards to access all fields in an object, e.g. `users.*.name` will access all `names` fields in all entries of the `users` array. When specifying nested paths, all matching values are flattened into an array set to a field named by the path."""

    text_fields: Optional[List[str]] = None
    r"""List of fields in the record that should be used to calculate the embedding. The field list is applied to all streams in the same way and non-existing fields are ignored. If none are defined, all fields are considered text fields. When specifying text fields, you can access nested fields in the record by using dot notation, e.g. `user.name` will access the `name` field in the `user` object. It's also possible to use wildcards to access all fields in an object, e.g. `users.*.name` will access all `names` fields in all entries of the `users` array."""

    text_splitter: Optional[DestinationPineconeTextSplitter] = None
    r"""Split text fields into chunks based on the specified method."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "chunk_overlap",
                "field_name_mappings",
                "metadata_fields",
                "text_fields",
                "text_splitter",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'destinationType' key instead.."
)
class DestinationPineconeTypedDict(TypedDict):
    r"""The configuration model for the Vector DB based destinations. This model is used to generate the UI for the destination configuration,
    as well as to provide type safety for the configuration passed to the destination.

    The configuration model is composed of four parts:
    * Processing configuration
    * Embedding configuration
    * Indexing configuration
    * Advanced configuration

    Processing, embedding and advanced configuration are provided by this base class, while the indexing configuration is provided by the destination connector in the sub class.
    """

    embedding: DestinationPineconeEmbeddingTypedDict
    r"""Embedding configuration"""
    indexing: DestinationPineconeIndexingTypedDict
    r"""Pinecone is a popular vector store that can be used to store and retrieve embeddings."""
    processing: DestinationPineconeProcessingConfigModelTypedDict
    destination_type: Pinecone
    omit_raw_text: NotRequired[bool]
    r"""Do not store the text that gets embedded along with the vector and the metadata in the destination. If set to true, only the vector and the metadata will be stored - in this case raw text for LLM use cases needs to be retrieved from another source."""


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'destinationType' key instead.."
)
class DestinationPinecone(BaseModel):
    r"""The configuration model for the Vector DB based destinations. This model is used to generate the UI for the destination configuration,
    as well as to provide type safety for the configuration passed to the destination.

    The configuration model is composed of four parts:
    * Processing configuration
    * Embedding configuration
    * Indexing configuration
    * Advanced configuration

    Processing, embedding and advanced configuration are provided by this base class, while the indexing configuration is provided by the destination connector in the sub class.
    """

    embedding: DestinationPineconeEmbedding
    r"""Embedding configuration"""

    indexing: DestinationPineconeIndexing
    r"""Pinecone is a popular vector store that can be used to store and retrieve embeddings."""

    processing: DestinationPineconeProcessingConfigModel

    DESTINATION_TYPE: Annotated[
        Annotated[Pinecone, AfterValidator(validate_const(Pinecone.PINECONE))],
        pydantic.Field(alias="destinationType"),
    ] = Pinecone.PINECONE

    omit_raw_text: Optional[bool] = False
    r"""Do not store the text that gets embedded along with the vector and the metadata in the destination. If set to true, only the vector and the metadata will be stored - in this case raw text for LLM use cases needs to be retrieved from another source."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["omit_raw_text"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    DestinationPineconeOpenAICompatible.model_rebuild()
except NameError:
    pass
try:
    DestinationPineconeAzureOpenAI.model_rebuild()
except NameError:
    pass
try:
    DestinationPineconeFake.model_rebuild()
except NameError:
    pass
try:
    DestinationPineconeCohere.model_rebuild()
except NameError:
    pass
try:
    DestinationPineconeOpenAI.model_rebuild()
except NameError:
    pass
try:
    DestinationPineconeByProgrammingLanguage.model_rebuild()
except NameError:
    pass
try:
    DestinationPineconeByMarkdownHeader.model_rebuild()
except NameError:
    pass
try:
    DestinationPineconeBySeparator.model_rebuild()
except NameError:
    pass
try:
    DestinationPinecone.model_rebuild()
except NameError:
    pass
