"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .rowfilteringoperationtype import RowFilteringOperationType
from airbyte_api.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class RowFilteringOperationEqualTypedDict(TypedDict):
    comparison_value: str
    r"""The value to compare the field against."""
    field_name: str
    r"""The name of the field to apply the operation on."""
    type: RowFilteringOperationType


class RowFilteringOperationEqual(BaseModel):
    comparison_value: Annotated[str, pydantic.Field(alias="comparisonValue")]
    r"""The value to compare the field against."""

    field_name: Annotated[str, pydantic.Field(alias="fieldName")]
    r"""The name of the field to apply the operation on."""

    type: RowFilteringOperationType


try:
    RowFilteringOperationEqual.model_rebuild()
except NameError:
    pass
