"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel
from airbyte_api.utils import validate_const
from datetime import datetime
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import Annotated, TypedDict


class Aircall(str, Enum):
    AIRCALL = "aircall"


class SourceAircallTypedDict(TypedDict):
    api_id: str
    r"""App ID found at settings https://dashboard.aircall.io/integrations/api-keys"""
    api_token: str
    r"""App token found at settings (Ref- https://dashboard.aircall.io/integrations/api-keys)"""
    start_date: datetime
    r"""Date time filter for incremental filter, Specify which date to extract from."""
    source_type: Aircall


class SourceAircall(BaseModel):
    api_id: str
    r"""App ID found at settings https://dashboard.aircall.io/integrations/api-keys"""

    api_token: str
    r"""App token found at settings (Ref- https://dashboard.aircall.io/integrations/api-keys)"""

    start_date: datetime
    r"""Date time filter for incremental filter, Specify which date to extract from."""

    SOURCE_TYPE: Annotated[
        Annotated[Aircall, AfterValidator(validate_const(Aircall.AIRCALL))],
        pydantic.Field(alias="sourceType"),
    ] = Aircall.AIRCALL


try:
    SourceAircall.model_rebuild()
except NameError:
    pass
