"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from airbyte_api import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Final


class Workramp(str, Enum):
    WORKRAMP = 'workramp'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class SourceWorkramp:
    academy_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('academy_id') }})
    r"""The id of the Academy"""
    api_key: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('api_key') }})
    r"""The API Token for Workramp"""
    SOURCE_TYPE: Final[Workramp] = dataclasses.field(default=Workramp.WORKRAMP, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('sourceType') }})
    

