"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from airbyte_api import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Final


class Dockerhub(str, Enum):
    DOCKERHUB = 'dockerhub'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class SourceDockerhub:
    docker_username: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('docker_username') }})
    r"""Username of DockerHub person or organization (for https://hub.docker.com/v2/repositories/USERNAME/ API call)"""
    SOURCE_TYPE: Final[Dockerhub] = dataclasses.field(default=Dockerhub.DOCKERHUB, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('sourceType') }})
    

