"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel
from airbyte_api.utils import validate_const
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import Annotated, TypedDict, deprecated


class Luma(str, Enum):
    LUMA = "luma"


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourceLumaTypedDict(TypedDict):
    api_key: str
    r"""Get your API key on lu.ma Calendars dashboard → Settings."""
    source_type: Luma


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourceLuma(BaseModel):
    api_key: str
    r"""Get your API key on lu.ma Calendars dashboard → Settings."""

    SOURCE_TYPE: Annotated[
        Annotated[Luma, AfterValidator(validate_const(Luma.LUMA))],
        pydantic.Field(alias="sourceType"),
    ] = Luma.LUMA


try:
    SourceLuma.model_rebuild()
except NameError:
    pass
