"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel
from airbyte_api.utils import validate_const
from datetime import datetime
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import Annotated, TypedDict


class Merge(str, Enum):
    MERGE = "merge"


class SourceMergeTypedDict(TypedDict):
    account_token: str
    r"""Link your other integrations with account credentials on accounts section to get account token (ref - https://app.merge.dev/linked-accounts/accounts)"""
    api_token: str
    r"""API token can be seen at  https://app.merge.dev/keys"""
    start_date: datetime
    r"""Date time filter for incremental filter, Specify which date to extract from."""
    source_type: Merge


class SourceMerge(BaseModel):
    account_token: str
    r"""Link your other integrations with account credentials on accounts section to get account token (ref - https://app.merge.dev/linked-accounts/accounts)"""

    api_token: str
    r"""API token can be seen at  https://app.merge.dev/keys"""

    start_date: datetime
    r"""Date time filter for incremental filter, Specify which date to extract from."""

    SOURCE_TYPE: Annotated[
        Annotated[Merge, AfterValidator(validate_const(Merge.MERGE))],
        pydantic.Field(alias="sourceType"),
    ] = Merge.MERGE


try:
    SourceMerge.model_rebuild()
except NameError:
    pass
