"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel
from airbyte_api.utils import validate_const
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import Annotated, TypedDict, deprecated


class Cin7(str, Enum):
    CIN7 = "cin7"


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourceCin7TypedDict(TypedDict):
    accountid: str
    r"""The ID associated with your account."""
    api_key: str
    r"""The API key associated with your account."""
    source_type: Cin7


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourceCin7(BaseModel):
    accountid: str
    r"""The ID associated with your account."""

    api_key: str
    r"""The API key associated with your account."""

    SOURCE_TYPE: Annotated[
        Annotated[Cin7, AfterValidator(validate_const(Cin7.CIN7))],
        pydantic.Field(alias="sourceType"),
    ] = Cin7.CIN7


try:
    SourceCin7.model_rebuild()
except NameError:
    pass
