"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel
from airbyte_api.utils import validate_const
from datetime import datetime
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import Annotated, TypedDict


class Outreach(str, Enum):
    OUTREACH = "outreach"


class SourceOutreachTypedDict(TypedDict):
    client_id: str
    r"""The Client ID of your Outreach developer application."""
    client_secret: str
    r"""The Client Secret of your Outreach developer application."""
    redirect_uri: str
    r"""A Redirect URI is the location where the authorization server sends the user once the app has been successfully authorized and granted an authorization code or access token."""
    refresh_token: str
    r"""The token for obtaining the new access token."""
    start_date: datetime
    r"""The date from which you'd like to replicate data for Outreach API, in the format YYYY-MM-DDT00:00:00.000Z. All data generated after this date will be replicated."""
    source_type: Outreach


class SourceOutreach(BaseModel):
    client_id: str
    r"""The Client ID of your Outreach developer application."""

    client_secret: str
    r"""The Client Secret of your Outreach developer application."""

    redirect_uri: str
    r"""A Redirect URI is the location where the authorization server sends the user once the app has been successfully authorized and granted an authorization code or access token."""

    refresh_token: str
    r"""The token for obtaining the new access token."""

    start_date: datetime
    r"""The date from which you'd like to replicate data for Outreach API, in the format YYYY-MM-DDT00:00:00.000Z. All data generated after this date will be replicated."""

    SOURCE_TYPE: Annotated[
        Annotated[Outreach, AfterValidator(validate_const(Outreach.OUTREACH))],
        pydantic.Field(alias="sourceType"),
    ] = Outreach.OUTREACH


try:
    SourceOutreach.model_rebuild()
except NameError:
    pass
