"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel, UNSET_SENTINEL
from airbyte_api.utils import validate_const
from datetime import datetime
from enum import Enum
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict, deprecated


class Resolution(str, Enum):
    HOUR = "hour"
    DAY = "day"
    WEEK = "week"


class Pingdom(str, Enum):
    PINGDOM = "pingdom"


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourcePingdomTypedDict(TypedDict):
    api_key: str
    start_date: datetime
    probes: NotRequired[str]
    resolution: NotRequired[Resolution]
    source_type: Pingdom


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourcePingdom(BaseModel):
    api_key: str

    start_date: datetime

    probes: Optional[str] = None

    resolution: Optional[Resolution] = Resolution.HOUR

    SOURCE_TYPE: Annotated[
        Annotated[Pingdom, AfterValidator(validate_const(Pingdom.PINGDOM))],
        pydantic.Field(alias="sourceType"),
    ] = Pingdom.PINGDOM

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["probes", "resolution"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SourcePingdom.model_rebuild()
except NameError:
    pass
