"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel
from airbyte_api.utils import validate_const
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import Annotated, TypedDict


class Dockerhub(str, Enum):
    DOCKERHUB = "dockerhub"


class SourceDockerhubTypedDict(TypedDict):
    docker_username: str
    r"""Username of DockerHub person or organization (for https://hub.docker.com/v2/repositories/USERNAME/ API call)"""
    source_type: Dockerhub


class SourceDockerhub(BaseModel):
    docker_username: str
    r"""Username of DockerHub person or organization (for https://hub.docker.com/v2/repositories/USERNAME/ API call)"""

    SOURCE_TYPE: Annotated[
        Annotated[Dockerhub, AfterValidator(validate_const(Dockerhub.DOCKERHUB))],
        pydantic.Field(alias="sourceType"),
    ] = Dockerhub.DOCKERHUB


try:
    SourceDockerhub.model_rebuild()
except NameError:
    pass
