"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel
from airbyte_api.utils import validate_const
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import Annotated, TypedDict, deprecated


class Printify(str, Enum):
    PRINTIFY = "printify"


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourcePrintifyTypedDict(TypedDict):
    api_token: str
    r"""Your Printify API token. Obtain it from your Printify account settings."""
    source_type: Printify


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourcePrintify(BaseModel):
    api_token: str
    r"""Your Printify API token. Obtain it from your Printify account settings."""

    SOURCE_TYPE: Annotated[
        Annotated[Printify, AfterValidator(validate_const(Printify.PRINTIFY))],
        pydantic.Field(alias="sourceType"),
    ] = Printify.PRINTIFY


try:
    SourcePrintify.model_rebuild()
except NameError:
    pass
