"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from airbyte_api import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Final, Optional


class MicrosoftDataverse(str, Enum):
    MICROSOFT_DATAVERSE = 'microsoft-dataverse'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class SourceMicrosoftDataverse:
    client_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('client_id') }})
    r"""App Registration Client Id"""
    client_secret_value: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('client_secret_value') }})
    r"""App Registration Client Secret"""
    tenant_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('tenant_id') }})
    r"""Tenant Id of your Microsoft Dataverse Instance"""
    url: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('url') }})
    r"""URL to Microsoft Dataverse API"""
    odata_maxpagesize: Optional[int] = dataclasses.field(default=5000, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('odata_maxpagesize'), 'exclude': lambda f: f is None }})
    r"""Max number of results per page. Default=5000"""
    SOURCE_TYPE: Final[MicrosoftDataverse] = dataclasses.field(default=MicrosoftDataverse.MICROSOFT_DATAVERSE, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('sourceType') }})
    

