"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel, UNSET_SENTINEL
from airbyte_api.utils import validate_const
from datetime import datetime
from enum import Enum
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FinancialModelling(str, Enum):
    FINANCIAL_MODELLING = "financial-modelling"


class TimeFrame(str, Enum):
    r"""For example 1min, 5min, 15min, 30min, 1hour, 4hour"""

    ONEMIN = "1min"
    FIVEMIN = "5min"
    FIFTEENMIN = "15min"
    THIRTYMIN = "30min"
    ONEHOUR = "1hour"
    FOURHOUR = "4hour"


class SourceFinancialModellingTypedDict(TypedDict):
    api_key: str
    start_date: datetime
    exchange: NotRequired[str]
    r"""The stock exchange : AMEX, AMS, AQS, ASX, ATH, BER, BME, BRU, BSE, BUD, BUE, BVC, CAI, CBOE, CNQ, CPH, DFM, DOH, DUS, DXE, EGX, EURONEXT, HAM, HEL, HKSE, ICE, IOB, IST, JKT, JNB, JPX, KLS, KOE, KSC, KUW, LSE, MCX, MEX, MIL, MUN, NASDAQ, NEO, NSE, NYSE, NZE, OEM, OQX, OSL, OTC, PNK, PRA, RIS, SAO, SAU, SES, SET, SGO, SHH, SHZ, SIX, STO, STU, TAI, TLV, TSX, TSXV, TWO, VIE, VSE, WSE, XETRA"""
    marketcaplowerthan: NotRequired[str]
    r"""Used in screener to filter out stocks with a market cap lower than the give marketcap"""
    marketcapmorethan: NotRequired[str]
    r"""Used in screener to filter out stocks with a market cap more than the give marketcap"""
    source_type: FinancialModelling
    time_frame: NotRequired[TimeFrame]
    r"""For example 1min, 5min, 15min, 30min, 1hour, 4hour"""


class SourceFinancialModelling(BaseModel):
    api_key: str

    start_date: datetime

    exchange: Optional[str] = "NASDAQ"
    r"""The stock exchange : AMEX, AMS, AQS, ASX, ATH, BER, BME, BRU, BSE, BUD, BUE, BVC, CAI, CBOE, CNQ, CPH, DFM, DOH, DUS, DXE, EGX, EURONEXT, HAM, HEL, HKSE, ICE, IOB, IST, JKT, JNB, JPX, KLS, KOE, KSC, KUW, LSE, MCX, MEX, MIL, MUN, NASDAQ, NEO, NSE, NYSE, NZE, OEM, OQX, OSL, OTC, PNK, PRA, RIS, SAO, SAU, SES, SET, SGO, SHH, SHZ, SIX, STO, STU, TAI, TLV, TSX, TSXV, TWO, VIE, VSE, WSE, XETRA"""

    marketcaplowerthan: Optional[str] = None
    r"""Used in screener to filter out stocks with a market cap lower than the give marketcap"""

    marketcapmorethan: Optional[str] = None
    r"""Used in screener to filter out stocks with a market cap more than the give marketcap"""

    SOURCE_TYPE: Annotated[
        Annotated[
            FinancialModelling,
            AfterValidator(validate_const(FinancialModelling.FINANCIAL_MODELLING)),
        ],
        pydantic.Field(alias="sourceType"),
    ] = FinancialModelling.FINANCIAL_MODELLING

    time_frame: Optional[TimeFrame] = TimeFrame.FOURHOUR
    r"""For example 1min, 5min, 15min, 30min, 1hour, 4hour"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["exchange", "marketcaplowerthan", "marketcapmorethan", "time_frame"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SourceFinancialModelling.model_rebuild()
except NameError:
    pass
