"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel, UNSET_SENTINEL
from airbyte_api.utils import validate_const
from datetime import datetime
from enum import Enum
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SourceWorkdayRestAuthenticationTypedDict(TypedDict):
    r"""Credentials for connecting to the Workday (REST) API."""

    access_token: str
    r"""Follow the instructions in the \"OAuth 2.0 in Postman - API Client for Integrations\" article in the Workday community docs to obtain access token."""


class SourceWorkdayRestAuthentication(BaseModel):
    r"""Credentials for connecting to the Workday (REST) API."""

    access_token: str
    r"""Follow the instructions in the \"OAuth 2.0 in Postman - API Client for Integrations\" article in the Workday community docs to obtain access token."""


class WorkdayRest(str, Enum):
    WORKDAY_REST = "workday-rest"


class SourceWorkdayRestTypedDict(TypedDict):
    credentials: SourceWorkdayRestAuthenticationTypedDict
    r"""Credentials for connecting to the Workday (REST) API."""
    host: str
    tenant_id: str
    num_workers: NotRequired[int]
    r"""The number of worker threads to use for the sync."""
    source_type: WorkdayRest
    start_date: NotRequired[datetime]
    r"""Rows after this date will be synced, default 2 years ago."""


class SourceWorkdayRest(BaseModel):
    credentials: SourceWorkdayRestAuthentication
    r"""Credentials for connecting to the Workday (REST) API."""

    host: str

    tenant_id: str

    num_workers: Optional[int] = 20
    r"""The number of worker threads to use for the sync."""

    SOURCE_TYPE: Annotated[
        Annotated[
            WorkdayRest, AfterValidator(validate_const(WorkdayRest.WORKDAY_REST))
        ],
        pydantic.Field(alias="sourceType"),
    ] = WorkdayRest.WORKDAY_REST

    start_date: Optional[datetime] = None
    r"""Rows after this date will be synced, default 2 years ago."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["num_workers", "start_date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SourceWorkdayRest.model_rebuild()
except NameError:
    pass
