"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel, UNSET_SENTINEL
from airbyte_api.utils import get_discriminator, parse_datetime, validate_const
from datetime import datetime
from enum import Enum
import pydantic
from pydantic import Discriminator, Tag, model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Optional, Union
from typing_extensions import (
    Annotated,
    NotRequired,
    TypeAliasType,
    TypedDict,
    deprecated,
)


class SourceConvertkitAuthTypeAPIKey(str, Enum):
    API_KEY = "api_key"


class SourceConvertkitAPIKeyTypedDict(TypedDict):
    api_key: NotRequired[str]
    r"""Kit/ConvertKit API Key"""
    auth_type: SourceConvertkitAuthTypeAPIKey


class SourceConvertkitAPIKey(BaseModel):
    api_key: Optional[str] = (
        "{{ config.get('credentials',{}).get('api_key') or config.get('api_secret') }}"
    )
    r"""Kit/ConvertKit API Key"""

    AUTH_TYPE: Annotated[
        Annotated[
            SourceConvertkitAuthTypeAPIKey,
            AfterValidator(validate_const(SourceConvertkitAuthTypeAPIKey.API_KEY)),
        ],
        pydantic.Field(alias="auth_type"),
    ] = SourceConvertkitAuthTypeAPIKey.API_KEY

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["api_key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceConvertkitAuthTypeOauth20(str, Enum):
    OAUTH2_0 = "oauth2.0"


class SourceConvertkitOAuth20TypedDict(TypedDict):
    client_id: str
    r"""The client ID of your OAuth application."""
    client_secret: str
    r"""The client secret of your OAuth application."""
    refresh_token: str
    r"""A current, non-expired refresh token genereted using the provided client ID and secret."""
    access_token: NotRequired[str]
    r"""An access token generated using the provided client information and refresh token."""
    auth_type: SourceConvertkitAuthTypeOauth20
    expires_at: NotRequired[datetime]
    r"""The time at which the current access token is set to expire"""


class SourceConvertkitOAuth20(BaseModel):
    client_id: str
    r"""The client ID of your OAuth application."""

    client_secret: str
    r"""The client secret of your OAuth application."""

    refresh_token: str
    r"""A current, non-expired refresh token genereted using the provided client ID and secret."""

    access_token: Optional[str] = None
    r"""An access token generated using the provided client information and refresh token."""

    AUTH_TYPE: Annotated[
        Annotated[
            SourceConvertkitAuthTypeOauth20,
            AfterValidator(validate_const(SourceConvertkitAuthTypeOauth20.OAUTH2_0)),
        ],
        pydantic.Field(alias="auth_type"),
    ] = SourceConvertkitAuthTypeOauth20.OAUTH2_0

    expires_at: Optional[datetime] = None
    r"""The time at which the current access token is set to expire"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["access_token", "expires_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


SourceConvertkitAuthenticationTypeTypedDict = TypeAliasType(
    "SourceConvertkitAuthenticationTypeTypedDict",
    Union[SourceConvertkitAPIKeyTypedDict, SourceConvertkitOAuth20TypedDict],
)


SourceConvertkitAuthenticationType = Annotated[
    Union[
        Annotated[SourceConvertkitOAuth20, Tag("oauth2.0")],
        Annotated[SourceConvertkitAPIKey, Tag("api_key")],
    ],
    Discriminator(lambda m: get_discriminator(m, "auth_type", "auth_type")),
]


class Convertkit(str, Enum):
    CONVERTKIT = "convertkit"


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourceConvertkitTypedDict(TypedDict):
    credentials: SourceConvertkitAuthenticationTypeTypedDict
    source_type: Convertkit
    start_date: NotRequired[datetime]


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourceConvertkit(BaseModel):
    credentials: SourceConvertkitAuthenticationType

    SOURCE_TYPE: Annotated[
        Annotated[Convertkit, AfterValidator(validate_const(Convertkit.CONVERTKIT))],
        pydantic.Field(alias="sourceType"),
    ] = Convertkit.CONVERTKIT

    start_date: Optional[datetime] = parse_datetime("2013-01-01T00:00:00Z")

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["start_date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SourceConvertkitAPIKey.model_rebuild()
except NameError:
    pass
try:
    SourceConvertkitOAuth20.model_rebuild()
except NameError:
    pass
try:
    SourceConvertkit.model_rebuild()
except NameError:
    pass
