"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel
from airbyte_api.utils import validate_const
from datetime import datetime
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import Annotated, TypedDict


class Svix(str, Enum):
    SVIX = "svix"


class SourceSvixTypedDict(TypedDict):
    api_key: str
    r"""API key or access token"""
    start_date: datetime
    source_type: Svix


class SourceSvix(BaseModel):
    api_key: str
    r"""API key or access token"""

    start_date: datetime

    SOURCE_TYPE: Annotated[
        Annotated[Svix, AfterValidator(validate_const(Svix.SVIX))],
        pydantic.Field(alias="sourceType"),
    ] = Svix.SVIX


try:
    SourceSvix.model_rebuild()
except NameError:
    pass
