"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel, UNSET_SENTINEL
from airbyte_api.utils import validate_const
from enum import Enum
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SourceGnewsCountry(str, Enum):
    r"""This parameter allows you to specify the country where the news articles returned by the API were published, the contents of the articles are not necessarily related to the specified country. You have to set as value the 2 letters code of the country you want to filter."""

    AU = "au"
    BR = "br"
    CA = "ca"
    CN = "cn"
    EG = "eg"
    FR = "fr"
    DE = "de"
    GR = "gr"
    HK = "hk"
    IN = "in"
    IE = "ie"
    IL = "il"
    IT = "it"
    JP = "jp"
    NL = "nl"
    NO = "no"
    PK = "pk"
    PE = "pe"
    PH = "ph"
    PT = "pt"
    RO = "ro"
    RU = "ru"
    SG = "sg"
    ES = "es"
    SE = "se"
    CH = "ch"
    TW = "tw"
    UA = "ua"
    GB = "gb"
    US = "us"


class In(str, Enum):
    TITLE = "title"
    DESCRIPTION = "description"
    CONTENT = "content"


class SourceGnewsLanguage(str, Enum):
    AR = "ar"
    ZH = "zh"
    NL = "nl"
    EN = "en"
    FR = "fr"
    DE = "de"
    EL = "el"
    HE = "he"
    HI = "hi"
    IT = "it"
    JA = "ja"
    ML = "ml"
    MR = "mr"
    NO = "no"
    PT = "pt"
    RO = "ro"
    RU = "ru"
    ES = "es"
    SV = "sv"
    TA = "ta"
    TE = "te"
    UK = "uk"


class Nullable(str, Enum):
    TITLE = "title"
    DESCRIPTION = "description"
    CONTENT = "content"


class SourceGnewsSortBy(str, Enum):
    r"""This parameter allows you to choose with which type of sorting the articles should be returned. Two values  are possible:
    - publishedAt = sort by publication date, the articles with the most recent
    publication date are returned first
    - relevance = sort by best match to keywords, the articles with the best
    match are returned first
    """

    PUBLISHED_AT = "publishedAt"
    RELEVANCE = "relevance"


class Gnews(str, Enum):
    GNEWS = "gnews"


class TopHeadlinesTopic(str, Enum):
    r"""This parameter allows you to change the category for the request."""

    BREAKING_NEWS = "breaking-news"
    WORLD = "world"
    NATION = "nation"
    BUSINESS = "business"
    TECHNOLOGY = "technology"
    ENTERTAINMENT = "entertainment"
    SPORTS = "sports"
    SCIENCE = "science"
    HEALTH = "health"


class SourceGnewsTypedDict(TypedDict):
    api_key: str
    r"""API Key"""
    query: str
    r"""This parameter allows you to specify your search keywords to find the news articles you are looking for. The keywords will be used to return the most relevant articles. It is possible to use logical operators  with keywords. - Phrase Search Operator: This operator allows you to make an exact search. Keywords surrounded by
    quotation marks are used to search for articles with the exact same keyword
    sequence.
    For example the query: \"Apple iPhone\" will return articles matching at
    least once this sequence of keywords. - Logical AND Operator: This operator allows you to make sure that several keywords are all used in the article
    search. By default the space character acts as an AND operator, it is
    possible to replace the space character
    by AND to obtain the same result. For example the query: Apple Microsoft
    is equivalent to Apple AND Microsoft - Logical OR Operator: This operator allows you to retrieve articles matching the keyword a or the keyword b.
    It is important to note that this operator has a higher precedence than
    the AND operator. For example the
    query: Apple OR Microsoft will return all articles matching the keyword
    Apple as well as all articles matching
    the keyword Microsoft
    - Logical NOT Operator: This operator allows you to remove from the results the articles corresponding to the
    specified keywords. To use it, you need to add NOT in front of each word
    or phrase surrounded by quotes.
    For example the query: Apple NOT iPhone will return all articles matching
    the keyword Apple but not the keyword
    iPhone
    """
    country: NotRequired[SourceGnewsCountry]
    r"""This parameter allows you to specify the country where the news articles returned by the API were published, the contents of the articles are not necessarily related to the specified country. You have to set as value the 2 letters code of the country you want to filter."""
    end_date: NotRequired[str]
    r"""This parameter allows you to filter the articles that have a publication date smaller than or equal to the  specified value. The date must respect the following format: YYYY-MM-DD hh:mm:ss (in UTC)"""
    in_: NotRequired[List[In]]
    r"""This parameter allows you to choose in which attributes the keywords are searched. The attributes that can be set are title, description and content. It is possible to combine several attributes."""
    language: NotRequired[SourceGnewsLanguage]
    nullable: NotRequired[List[Nullable]]
    r"""This parameter allows you to specify the attributes that you allow to return null values. The attributes that  can be set are title, description and content. It is possible to combine several attributes"""
    sortby: NotRequired[SourceGnewsSortBy]
    r"""This parameter allows you to choose with which type of sorting the articles should be returned. Two values  are possible:
    - publishedAt = sort by publication date, the articles with the most recent
    publication date are returned first
    - relevance = sort by best match to keywords, the articles with the best
    match are returned first
    """
    source_type: Gnews
    start_date: NotRequired[str]
    r"""This parameter allows you to filter the articles that have a publication date greater than or equal to the  specified value. The date must respect the following format: YYYY-MM-DD hh:mm:ss (in UTC)"""
    top_headlines_query: NotRequired[str]
    r"""This parameter allows you to specify your search keywords to find the news articles you are looking for. The keywords will be used to return the most relevant articles. It is possible to use logical operators  with keywords. - Phrase Search Operator: This operator allows you to make an exact search. Keywords surrounded by
    quotation marks are used to search for articles with the exact same keyword
    sequence.
    For example the query: \"Apple iPhone\" will return articles matching at
    least once this sequence of keywords. - Logical AND Operator: This operator allows you to make sure that several keywords are all used in the article
    search. By default the space character acts as an AND operator, it is
    possible to replace the space character
    by AND to obtain the same result. For example the query: Apple Microsoft
    is equivalent to Apple AND Microsoft - Logical OR Operator: This operator allows you to retrieve articles matching the keyword a or the keyword b.
    It is important to note that this operator has a higher precedence than
    the AND operator. For example the
    query: Apple OR Microsoft will return all articles matching the keyword
    Apple as well as all articles matching
    the keyword Microsoft
    - Logical NOT Operator: This operator allows you to remove from the results the articles corresponding to the
    specified keywords. To use it, you need to add NOT in front of each word
    or phrase surrounded by quotes.
    For example the query: Apple NOT iPhone will return all articles matching
    the keyword Apple but not the keyword
    iPhone
    """
    top_headlines_topic: NotRequired[TopHeadlinesTopic]
    r"""This parameter allows you to change the category for the request."""


class SourceGnews(BaseModel):
    api_key: str
    r"""API Key"""

    query: str
    r"""This parameter allows you to specify your search keywords to find the news articles you are looking for. The keywords will be used to return the most relevant articles. It is possible to use logical operators  with keywords. - Phrase Search Operator: This operator allows you to make an exact search. Keywords surrounded by
    quotation marks are used to search for articles with the exact same keyword
    sequence.
    For example the query: \"Apple iPhone\" will return articles matching at
    least once this sequence of keywords. - Logical AND Operator: This operator allows you to make sure that several keywords are all used in the article
    search. By default the space character acts as an AND operator, it is
    possible to replace the space character
    by AND to obtain the same result. For example the query: Apple Microsoft
    is equivalent to Apple AND Microsoft - Logical OR Operator: This operator allows you to retrieve articles matching the keyword a or the keyword b.
    It is important to note that this operator has a higher precedence than
    the AND operator. For example the
    query: Apple OR Microsoft will return all articles matching the keyword
    Apple as well as all articles matching
    the keyword Microsoft
    - Logical NOT Operator: This operator allows you to remove from the results the articles corresponding to the
    specified keywords. To use it, you need to add NOT in front of each word
    or phrase surrounded by quotes.
    For example the query: Apple NOT iPhone will return all articles matching
    the keyword Apple but not the keyword
    iPhone
    """

    country: Optional[SourceGnewsCountry] = None
    r"""This parameter allows you to specify the country where the news articles returned by the API were published, the contents of the articles are not necessarily related to the specified country. You have to set as value the 2 letters code of the country you want to filter."""

    end_date: Optional[str] = None
    r"""This parameter allows you to filter the articles that have a publication date smaller than or equal to the  specified value. The date must respect the following format: YYYY-MM-DD hh:mm:ss (in UTC)"""

    in_: Annotated[Optional[List[In]], pydantic.Field(alias="in")] = None
    r"""This parameter allows you to choose in which attributes the keywords are searched. The attributes that can be set are title, description and content. It is possible to combine several attributes."""

    language: Optional[SourceGnewsLanguage] = None

    nullable: Optional[List[Nullable]] = None
    r"""This parameter allows you to specify the attributes that you allow to return null values. The attributes that  can be set are title, description and content. It is possible to combine several attributes"""

    sortby: Optional[SourceGnewsSortBy] = None
    r"""This parameter allows you to choose with which type of sorting the articles should be returned. Two values  are possible:
    - publishedAt = sort by publication date, the articles with the most recent
    publication date are returned first
    - relevance = sort by best match to keywords, the articles with the best
    match are returned first
    """

    SOURCE_TYPE: Annotated[
        Annotated[Gnews, AfterValidator(validate_const(Gnews.GNEWS))],
        pydantic.Field(alias="sourceType"),
    ] = Gnews.GNEWS

    start_date: Optional[str] = None
    r"""This parameter allows you to filter the articles that have a publication date greater than or equal to the  specified value. The date must respect the following format: YYYY-MM-DD hh:mm:ss (in UTC)"""

    top_headlines_query: Optional[str] = None
    r"""This parameter allows you to specify your search keywords to find the news articles you are looking for. The keywords will be used to return the most relevant articles. It is possible to use logical operators  with keywords. - Phrase Search Operator: This operator allows you to make an exact search. Keywords surrounded by
    quotation marks are used to search for articles with the exact same keyword
    sequence.
    For example the query: \"Apple iPhone\" will return articles matching at
    least once this sequence of keywords. - Logical AND Operator: This operator allows you to make sure that several keywords are all used in the article
    search. By default the space character acts as an AND operator, it is
    possible to replace the space character
    by AND to obtain the same result. For example the query: Apple Microsoft
    is equivalent to Apple AND Microsoft - Logical OR Operator: This operator allows you to retrieve articles matching the keyword a or the keyword b.
    It is important to note that this operator has a higher precedence than
    the AND operator. For example the
    query: Apple OR Microsoft will return all articles matching the keyword
    Apple as well as all articles matching
    the keyword Microsoft
    - Logical NOT Operator: This operator allows you to remove from the results the articles corresponding to the
    specified keywords. To use it, you need to add NOT in front of each word
    or phrase surrounded by quotes.
    For example the query: Apple NOT iPhone will return all articles matching
    the keyword Apple but not the keyword
    iPhone
    """

    top_headlines_topic: Optional[TopHeadlinesTopic] = None
    r"""This parameter allows you to change the category for the request."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "country",
                "end_date",
                "in",
                "language",
                "nullable",
                "sortby",
                "start_date",
                "top_headlines_query",
                "top_headlines_topic",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SourceGnews.model_rebuild()
except NameError:
    pass
