"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel
from airbyte_api.utils import validate_const
from datetime import datetime
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import Annotated, TypedDict


class Entity(str, Enum):
    PARTIES = "parties"
    OPPORTUNITIES = "opportunities"
    KASES = "kases"


class CapsuleCrm(str, Enum):
    CAPSULE_CRM = "capsule-crm"


class SourceCapsuleCrmTypedDict(TypedDict):
    bearer_token: str
    r"""Bearer token to authenticate API requests. Generate it from the 'My Preferences' > 'API Authentication Tokens' page in your Capsule account."""
    entity: Entity
    start_date: datetime
    source_type: CapsuleCrm


class SourceCapsuleCrm(BaseModel):
    bearer_token: str
    r"""Bearer token to authenticate API requests. Generate it from the 'My Preferences' > 'API Authentication Tokens' page in your Capsule account."""

    entity: Entity

    start_date: datetime

    SOURCE_TYPE: Annotated[
        Annotated[CapsuleCrm, AfterValidator(validate_const(CapsuleCrm.CAPSULE_CRM))],
        pydantic.Field(alias="sourceType"),
    ] = CapsuleCrm.CAPSULE_CRM


try:
    SourceCapsuleCrm.model_rebuild()
except NameError:
    pass
