"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from airbyte_api import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Final


class Toggl(str, Enum):
    TOGGL = 'toggl'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class SourceToggl:
    api_token: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('api_token') }})
    r"""Your API Token. See <a href=\\"https://developers.track.toggl.com/docs/authentication\\">here</a>. The token is case sensitive."""
    end_date: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('end_date') }})
    r"""To retrieve time entries created before the given date (inclusive)."""
    organization_id: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('organization_id') }})
    r"""Your organization id. See <a href=\\"https://developers.track.toggl.com/docs/organization\\">here</a>."""
    start_date: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('start_date') }})
    r"""To retrieve time entries created after the given date (inclusive)."""
    workspace_id: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('workspace_id') }})
    r"""Your workspace id. See <a href=\\"https://developers.track.toggl.com/docs/workspaces\\">here</a>."""
    SOURCE_TYPE: Final[Toggl] = dataclasses.field(default=Toggl.TOGGL, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('sourceType') }})
    

