"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel, UNSET_SENTINEL
from airbyte_api.utils import get_discriminator, validate_const
from datetime import date
from enum import Enum
import pydantic
from pydantic import Discriminator, Tag, model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class SourceGoogleSearchConsoleAuthenticationTypeAuthorizationAuthType(str, Enum):
    SERVICE = "Service"


class AuthenticationTypeServiceAccountKeyAuthenticationTypedDict(TypedDict):
    email: str
    r"""The email of the user which has permissions to access the Google Workspace Admin APIs."""
    service_account_info: str
    r"""The JSON key of the service account to use for authorization. Read more <a href=\"https://cloud.google.com/iam/docs/creating-managing-service-account-keys\">here</a>."""
    auth_type: SourceGoogleSearchConsoleAuthenticationTypeAuthorizationAuthType


class AuthenticationTypeServiceAccountKeyAuthentication(BaseModel):
    email: str
    r"""The email of the user which has permissions to access the Google Workspace Admin APIs."""

    service_account_info: str
    r"""The JSON key of the service account to use for authorization. Read more <a href=\"https://cloud.google.com/iam/docs/creating-managing-service-account-keys\">here</a>."""

    AUTH_TYPE: Annotated[
        Annotated[
            SourceGoogleSearchConsoleAuthenticationTypeAuthorizationAuthType,
            AfterValidator(
                validate_const(
                    SourceGoogleSearchConsoleAuthenticationTypeAuthorizationAuthType.SERVICE
                )
            ),
        ],
        pydantic.Field(alias="auth_type"),
    ] = SourceGoogleSearchConsoleAuthenticationTypeAuthorizationAuthType.SERVICE


class SourceGoogleSearchConsoleAuthenticationTypeAuthType(str, Enum):
    CLIENT = "Client"


class AuthenticationTypeOAuthTypedDict(TypedDict):
    client_id: str
    r"""The client ID of your Google Search Console developer application. Read more <a href=\"https://developers.google.com/webmaster-tools/v1/how-tos/authorizing\">here</a>."""
    client_secret: str
    r"""The client secret of your Google Search Console developer application. Read more <a href=\"https://developers.google.com/webmaster-tools/v1/how-tos/authorizing\">here</a>."""
    refresh_token: str
    r"""The token for obtaining a new access token. Read more <a href=\"https://developers.google.com/webmaster-tools/v1/how-tos/authorizing\">here</a>."""
    access_token: NotRequired[str]
    r"""Access token for making authenticated requests. Read more <a href=\"https://developers.google.com/webmaster-tools/v1/how-tos/authorizing\">here</a>."""
    auth_type: SourceGoogleSearchConsoleAuthenticationTypeAuthType


class AuthenticationTypeOAuth(BaseModel):
    client_id: str
    r"""The client ID of your Google Search Console developer application. Read more <a href=\"https://developers.google.com/webmaster-tools/v1/how-tos/authorizing\">here</a>."""

    client_secret: str
    r"""The client secret of your Google Search Console developer application. Read more <a href=\"https://developers.google.com/webmaster-tools/v1/how-tos/authorizing\">here</a>."""

    refresh_token: str
    r"""The token for obtaining a new access token. Read more <a href=\"https://developers.google.com/webmaster-tools/v1/how-tos/authorizing\">here</a>."""

    access_token: Optional[str] = None
    r"""Access token for making authenticated requests. Read more <a href=\"https://developers.google.com/webmaster-tools/v1/how-tos/authorizing\">here</a>."""

    AUTH_TYPE: Annotated[
        Annotated[
            SourceGoogleSearchConsoleAuthenticationTypeAuthType,
            AfterValidator(
                validate_const(
                    SourceGoogleSearchConsoleAuthenticationTypeAuthType.CLIENT
                )
            ),
        ],
        pydantic.Field(alias="auth_type"),
    ] = SourceGoogleSearchConsoleAuthenticationTypeAuthType.CLIENT

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["access_token"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


SourceGoogleSearchConsoleAuthenticationTypeTypedDict = TypeAliasType(
    "SourceGoogleSearchConsoleAuthenticationTypeTypedDict",
    Union[
        AuthenticationTypeServiceAccountKeyAuthenticationTypedDict,
        AuthenticationTypeOAuthTypedDict,
    ],
)


SourceGoogleSearchConsoleAuthenticationType = Annotated[
    Union[
        Annotated[AuthenticationTypeOAuth, Tag("Client")],
        Annotated[AuthenticationTypeServiceAccountKeyAuthentication, Tag("Service")],
    ],
    Discriminator(lambda m: get_discriminator(m, "auth_type", "auth_type")),
]


class SourceGoogleSearchConsoleValidEnums(str, Enum):
    r"""An enumeration of dimensions."""

    COUNTRY = "country"
    DATE = "date"
    DEVICE = "device"
    PAGE = "page"
    QUERY = "query"


class SourceGoogleSearchConsoleCustomReportConfigTypedDict(TypedDict):
    dimensions: List[SourceGoogleSearchConsoleValidEnums]
    r"""A list of available dimensions. Please note, that for technical reasons `date` is the default dimension which will be included in your query whether you specify it or not. Primary key will consist of your custom dimensions and the default dimension along with `site_url` and `search_type`."""
    name: str
    r"""The name of the custom report, this name would be used as stream name"""


class SourceGoogleSearchConsoleCustomReportConfig(BaseModel):
    dimensions: List[SourceGoogleSearchConsoleValidEnums]
    r"""A list of available dimensions. Please note, that for technical reasons `date` is the default dimension which will be included in your query whether you specify it or not. Primary key will consist of your custom dimensions and the default dimension along with `site_url` and `search_type`."""

    name: str
    r"""The name of the custom report, this name would be used as stream name"""


class DataFreshness(str, Enum):
    r"""If set to 'final', the returned data will include only finalized, stable data. If set to 'all', fresh data will be included. When using Incremental sync mode, we do not recommend setting this parameter to 'all' as it may cause data loss. More information can be found in our <a href='https://docs.airbyte.com/integrations/source/google-search-console'>full documentation</a>."""

    FINAL = "final"
    ALL = "all"


class SourceGoogleSearchConsoleGoogleSearchConsole(str, Enum):
    GOOGLE_SEARCH_CONSOLE = "google-search-console"


class SourceGoogleSearchConsoleTypedDict(TypedDict):
    authorization: SourceGoogleSearchConsoleAuthenticationTypeTypedDict
    site_urls: List[str]
    r"""The URLs of the website property attached to your GSC account. Learn more about properties <a href=\"https://support.google.com/webmasters/answer/34592?hl=en\">here</a>."""
    always_use_aggregation_type_auto: NotRequired[bool]
    r"""Some search analytics streams fail with a 400 error if the specified `aggregationType` is not supported. This is customer implementation dependent and if this error is encountered, enable this setting which will override the existing `aggregationType` to use `auto` which should resolve the stream errors."""
    custom_reports_array: NotRequired[
        List[SourceGoogleSearchConsoleCustomReportConfigTypedDict]
    ]
    r"""You can add your Custom Analytics report by creating one."""
    data_state: NotRequired[DataFreshness]
    r"""If set to 'final', the returned data will include only finalized, stable data. If set to 'all', fresh data will be included. When using Incremental sync mode, we do not recommend setting this parameter to 'all' as it may cause data loss. More information can be found in our <a href='https://docs.airbyte.com/integrations/source/google-search-console'>full documentation</a>."""
    end_date: NotRequired[date]
    r"""UTC date in the format YYYY-MM-DD. Any data created after this date will not be replicated. Must be greater or equal to the start date field. Leaving this field blank will replicate all data from the start date onward."""
    num_workers: NotRequired[int]
    r"""The number of worker threads to use for the sync. For more details on Google Search Console rate limits, refer to the <a href=\"https://developers.google.com/webmaster-tools/limits\">docs</a>."""
    source_type: SourceGoogleSearchConsoleGoogleSearchConsole
    start_date: NotRequired[date]
    r"""UTC date in the format YYYY-MM-DD. Any data before this date will not be replicated."""


class SourceGoogleSearchConsole(BaseModel):
    authorization: SourceGoogleSearchConsoleAuthenticationType

    site_urls: List[str]
    r"""The URLs of the website property attached to your GSC account. Learn more about properties <a href=\"https://support.google.com/webmasters/answer/34592?hl=en\">here</a>."""

    always_use_aggregation_type_auto: Optional[bool] = False
    r"""Some search analytics streams fail with a 400 error if the specified `aggregationType` is not supported. This is customer implementation dependent and if this error is encountered, enable this setting which will override the existing `aggregationType` to use `auto` which should resolve the stream errors."""

    custom_reports_array: Optional[
        List[SourceGoogleSearchConsoleCustomReportConfig]
    ] = None
    r"""You can add your Custom Analytics report by creating one."""

    data_state: Optional[DataFreshness] = DataFreshness.FINAL
    r"""If set to 'final', the returned data will include only finalized, stable data. If set to 'all', fresh data will be included. When using Incremental sync mode, we do not recommend setting this parameter to 'all' as it may cause data loss. More information can be found in our <a href='https://docs.airbyte.com/integrations/source/google-search-console'>full documentation</a>."""

    end_date: Optional[date] = None
    r"""UTC date in the format YYYY-MM-DD. Any data created after this date will not be replicated. Must be greater or equal to the start date field. Leaving this field blank will replicate all data from the start date onward."""

    num_workers: Optional[int] = 40
    r"""The number of worker threads to use for the sync. For more details on Google Search Console rate limits, refer to the <a href=\"https://developers.google.com/webmaster-tools/limits\">docs</a>."""

    SOURCE_TYPE: Annotated[
        Annotated[
            SourceGoogleSearchConsoleGoogleSearchConsole,
            AfterValidator(
                validate_const(
                    SourceGoogleSearchConsoleGoogleSearchConsole.GOOGLE_SEARCH_CONSOLE
                )
            ),
        ],
        pydantic.Field(alias="sourceType"),
    ] = SourceGoogleSearchConsoleGoogleSearchConsole.GOOGLE_SEARCH_CONSOLE

    start_date: Optional[date] = date.fromisoformat("2021-01-01")
    r"""UTC date in the format YYYY-MM-DD. Any data before this date will not be replicated."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "always_use_aggregation_type_auto",
                "custom_reports_array",
                "data_state",
                "end_date",
                "num_workers",
                "start_date",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AuthenticationTypeServiceAccountKeyAuthentication.model_rebuild()
except NameError:
    pass
try:
    AuthenticationTypeOAuth.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleSearchConsole.model_rebuild()
except NameError:
    pass
