"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from airbyte_api import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Final


class Systeme(str, Enum):
    SYSTEME = 'systeme'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class SourceSysteme:
    api_key: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('api_key') }})
    SOURCE_TYPE: Final[Systeme] = dataclasses.field(default=Systeme.SYSTEME, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('sourceType') }})
    

