"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel, UNSET_SENTINEL
from airbyte_api.utils import validate_const
from enum import Enum
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict, deprecated


class Faker(str, Enum):
    FAKER = "faker"


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourceFakerTypedDict(TypedDict):
    always_updated: NotRequired[bool]
    r"""Should the updated_at values for every record be new each sync?  Setting this to false will case the source to stop emitting records after COUNT records have been emitted."""
    count: NotRequired[int]
    r"""How many users should be generated in total. The purchases table will be scaled to match, with 10 purchases created per 10 users. This setting does not apply to the products stream."""
    parallelism: NotRequired[int]
    r"""How many parallel workers should we use to generate fake data?  Choose a value equal to the number of CPUs you will allocate to this source."""
    records_per_slice: NotRequired[int]
    r"""How many fake records will be in each page (stream slice), before a state message is emitted?"""
    seed: NotRequired[int]
    r"""Manually control the faker random seed to return the same values on subsequent runs (leave -1 for random)"""
    source_type: Faker


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourceFaker(BaseModel):
    always_updated: Optional[bool] = True
    r"""Should the updated_at values for every record be new each sync?  Setting this to false will case the source to stop emitting records after COUNT records have been emitted."""

    count: Optional[int] = 1000
    r"""How many users should be generated in total. The purchases table will be scaled to match, with 10 purchases created per 10 users. This setting does not apply to the products stream."""

    parallelism: Optional[int] = 4
    r"""How many parallel workers should we use to generate fake data?  Choose a value equal to the number of CPUs you will allocate to this source."""

    records_per_slice: Optional[int] = 1000
    r"""How many fake records will be in each page (stream slice), before a state message is emitted?"""

    seed: Optional[int] = -1
    r"""Manually control the faker random seed to return the same values on subsequent runs (leave -1 for random)"""

    SOURCE_TYPE: Annotated[
        Annotated[Faker, AfterValidator(validate_const(Faker.FAKER))],
        pydantic.Field(alias="sourceType"),
    ] = Faker.FAKER

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["always_updated", "count", "parallelism", "records_per_slice", "seed"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SourceFaker.model_rebuild()
except NameError:
    pass
