"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from airbyte_api import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Final


class Flowlu(str, Enum):
    FLOWLU = 'flowlu'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class SourceFlowlu:
    api_key: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('api_key') }})
    r"""The API key to use for authentication"""
    company: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('company') }})
    SOURCE_TYPE: Final[Flowlu] = dataclasses.field(default=Flowlu.FLOWLU, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('sourceType') }})
    

