"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel
from airbyte_api.utils import validate_const
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import Annotated, TypedDict, deprecated


class K6Cloud(str, Enum):
    K6_CLOUD = "k6-cloud"


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourceK6CloudTypedDict(TypedDict):
    api_token: str
    r"""Your API Token. See <a href=\"https://k6.io/docs/cloud/integrations/token/\">here</a>. The key is case sensitive."""
    source_type: K6Cloud


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourceK6Cloud(BaseModel):
    api_token: str
    r"""Your API Token. See <a href=\"https://k6.io/docs/cloud/integrations/token/\">here</a>. The key is case sensitive."""

    SOURCE_TYPE: Annotated[
        Annotated[K6Cloud, AfterValidator(validate_const(K6Cloud.K6_CLOUD))],
        pydantic.Field(alias="sourceType"),
    ] = K6Cloud.K6_CLOUD


try:
    SourceK6Cloud.model_rebuild()
except NameError:
    pass
