"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel, UNSET_SENTINEL
from airbyte_api.utils import validate_const
from enum import Enum
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict, deprecated


class Harness(str, Enum):
    HARNESS = "harness"


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourceHarnessTypedDict(TypedDict):
    account_id: str
    r"""Harness Account ID"""
    api_key: str
    api_url: NotRequired[str]
    r"""The API URL for fetching data from Harness"""
    source_type: Harness


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourceHarness(BaseModel):
    account_id: str
    r"""Harness Account ID"""

    api_key: str

    api_url: Optional[str] = "https://app.harness.io"
    r"""The API URL for fetching data from Harness"""

    SOURCE_TYPE: Annotated[
        Annotated[Harness, AfterValidator(validate_const(Harness.HARNESS))],
        pydantic.Field(alias="sourceType"),
    ] = Harness.HARNESS

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["api_url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SourceHarness.model_rebuild()
except NameError:
    pass
