"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from airbyte_api import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Final


class Hellobaton(str, Enum):
    HELLOBATON = 'hellobaton'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class SourceHellobaton:
    api_key: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('api_key') }})
    r"""authentication key required to access the api endpoints"""
    company: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('company') }})
    r"""Company name that generates your base api url"""
    SOURCE_TYPE: Final[Hellobaton] = dataclasses.field(default=Hellobaton.HELLOBATON, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('sourceType') }})
    

