"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel
from airbyte_api.utils import validate_const
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import Annotated, TypedDict, deprecated


class Omnisend(str, Enum):
    OMNISEND = "omnisend"


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourceOmnisendTypedDict(TypedDict):
    api_key: str
    r"""API Key"""
    source_type: Omnisend


@deprecated(
    "warning: ** DEPRECATED ** - Typed connector configuration models are deprecated and will be removed in v1.1.0. Pass configuration as a plain dict with a required 'sourceType' key instead.."
)
class SourceOmnisend(BaseModel):
    api_key: str
    r"""API Key"""

    SOURCE_TYPE: Annotated[
        Annotated[Omnisend, AfterValidator(validate_const(Omnisend.OMNISEND))],
        pydantic.Field(alias="sourceType"),
    ] = Omnisend.OMNISEND


try:
    SourceOmnisend.model_rebuild()
except NameError:
    pass
