"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel, UNSET_SENTINEL
from airbyte_api.utils import validate_const
from datetime import datetime
from enum import Enum
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class SourceAzureBlobStorageSchemasCredentialsAuthType(str, Enum):
    STORAGE_ACCOUNT_KEY = "storage_account_key"


class AuthenticateViaStorageAccountKeyTypedDict(TypedDict):
    azure_blob_storage_account_key: str
    r"""The Azure blob storage account key."""
    auth_type: SourceAzureBlobStorageSchemasCredentialsAuthType


class AuthenticateViaStorageAccountKey(BaseModel):
    azure_blob_storage_account_key: str
    r"""The Azure blob storage account key."""

    AUTH_TYPE: Annotated[
        Annotated[
            Optional[SourceAzureBlobStorageSchemasCredentialsAuthType],
            AfterValidator(
                validate_const(
                    SourceAzureBlobStorageSchemasCredentialsAuthType.STORAGE_ACCOUNT_KEY
                )
            ),
        ],
        pydantic.Field(alias="auth_type"),
    ] = SourceAzureBlobStorageSchemasCredentialsAuthType.STORAGE_ACCOUNT_KEY

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["auth_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceAzureBlobStorageSchemasAuthType(str, Enum):
    CLIENT_CREDENTIALS = "client_credentials"


class AuthenticateViaClientCredentialsTypedDict(TypedDict):
    app_client_id: str
    r"""Client ID of your Microsoft developer application"""
    app_client_secret: str
    r"""Client Secret of your Microsoft developer application"""
    app_tenant_id: str
    r"""Tenant ID of the Microsoft Azure Application"""
    auth_type: SourceAzureBlobStorageSchemasAuthType


class AuthenticateViaClientCredentials(BaseModel):
    app_client_id: str
    r"""Client ID of your Microsoft developer application"""

    app_client_secret: str
    r"""Client Secret of your Microsoft developer application"""

    app_tenant_id: str
    r"""Tenant ID of the Microsoft Azure Application"""

    AUTH_TYPE: Annotated[
        Annotated[
            Optional[SourceAzureBlobStorageSchemasAuthType],
            AfterValidator(
                validate_const(SourceAzureBlobStorageSchemasAuthType.CLIENT_CREDENTIALS)
            ),
        ],
        pydantic.Field(alias="auth_type"),
    ] = SourceAzureBlobStorageSchemasAuthType.CLIENT_CREDENTIALS

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["auth_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceAzureBlobStorageAuthType(str, Enum):
    OAUTH2 = "oauth2"


class AuthenticateViaOauth2TypedDict(TypedDict):
    client_id: str
    r"""Client ID of your Microsoft developer application"""
    client_secret: str
    r"""Client Secret of your Microsoft developer application"""
    refresh_token: str
    r"""Refresh Token of your Microsoft developer application"""
    tenant_id: str
    r"""Tenant ID of the Microsoft Azure Application user"""
    auth_type: SourceAzureBlobStorageAuthType


class AuthenticateViaOauth2(BaseModel):
    client_id: str
    r"""Client ID of your Microsoft developer application"""

    client_secret: str
    r"""Client Secret of your Microsoft developer application"""

    refresh_token: str
    r"""Refresh Token of your Microsoft developer application"""

    tenant_id: str
    r"""Tenant ID of the Microsoft Azure Application user"""

    AUTH_TYPE: Annotated[
        Annotated[
            Optional[SourceAzureBlobStorageAuthType],
            AfterValidator(validate_const(SourceAzureBlobStorageAuthType.OAUTH2)),
        ],
        pydantic.Field(alias="auth_type"),
    ] = SourceAzureBlobStorageAuthType.OAUTH2

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["auth_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


SourceAzureBlobStorageAuthenticationTypedDict = TypeAliasType(
    "SourceAzureBlobStorageAuthenticationTypedDict",
    Union[
        AuthenticateViaStorageAccountKeyTypedDict,
        AuthenticateViaClientCredentialsTypedDict,
        AuthenticateViaOauth2TypedDict,
    ],
)
r"""Credentials for connecting to the Azure Blob Storage"""


SourceAzureBlobStorageAuthentication = TypeAliasType(
    "SourceAzureBlobStorageAuthentication",
    Union[
        AuthenticateViaStorageAccountKey,
        AuthenticateViaClientCredentials,
        AuthenticateViaOauth2,
    ],
)
r"""Credentials for connecting to the Azure Blob Storage"""


class SourceAzureBlobStorageAzureBlobStorage(str, Enum):
    AZURE_BLOB_STORAGE = "azure-blob-storage"


class SourceAzureBlobStorageSchemasStreamsFormatFormatFiletype(str, Enum):
    EXCEL = "excel"


class ExcelFormatTypedDict(TypedDict):
    filetype: SourceAzureBlobStorageSchemasStreamsFormatFormatFiletype


class ExcelFormat(BaseModel):
    FILETYPE: Annotated[
        Annotated[
            Optional[SourceAzureBlobStorageSchemasStreamsFormatFormatFiletype],
            AfterValidator(
                validate_const(
                    SourceAzureBlobStorageSchemasStreamsFormatFormatFiletype.EXCEL
                )
            ),
        ],
        pydantic.Field(alias="filetype"),
    ] = SourceAzureBlobStorageSchemasStreamsFormatFormatFiletype.EXCEL

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["filetype"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceAzureBlobStorageSchemasStreamsFormatFiletype(str, Enum):
    UNSTRUCTURED = "unstructured"


class SourceAzureBlobStorageMode(str, Enum):
    LOCAL = "local"


class LocalTypedDict(TypedDict):
    r"""Process files locally, supporting `fast` and `ocr` modes. This is the default option."""

    mode: SourceAzureBlobStorageMode


class Local(BaseModel):
    r"""Process files locally, supporting `fast` and `ocr` modes. This is the default option."""

    MODE: Annotated[
        Annotated[
            Optional[SourceAzureBlobStorageMode],
            AfterValidator(validate_const(SourceAzureBlobStorageMode.LOCAL)),
        ],
        pydantic.Field(alias="mode"),
    ] = SourceAzureBlobStorageMode.LOCAL

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mode"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ProcessingTypedDict = LocalTypedDict
r"""Processing configuration"""


Processing = Local
r"""Processing configuration"""


class ParsingStrategy(str, Enum):
    r"""The strategy used to parse documents. `fast` extracts text directly from the document which doesn't work for all files. `ocr_only` is more reliable, but slower. `hi_res` is the most reliable, but requires an API key and a hosted instance of unstructured and can't be used with local mode. See the unstructured.io documentation for more details: https://unstructured-io.github.io/unstructured/core/partition.html#partition-pdf"""

    AUTO = "auto"
    FAST = "fast"
    OCR_ONLY = "ocr_only"
    HI_RES = "hi_res"


class UnstructuredDocumentFormatTypedDict(TypedDict):
    r"""Extract text from document formats (.pdf, .docx, .md, .pptx) and emit as one record per file."""

    filetype: SourceAzureBlobStorageSchemasStreamsFormatFiletype
    processing: NotRequired[ProcessingTypedDict]
    r"""Processing configuration"""
    skip_unprocessable_files: NotRequired[bool]
    r"""If true, skip files that cannot be parsed and pass the error message along as the _ab_source_file_parse_error field. If false, fail the sync."""
    strategy: NotRequired[ParsingStrategy]
    r"""The strategy used to parse documents. `fast` extracts text directly from the document which doesn't work for all files. `ocr_only` is more reliable, but slower. `hi_res` is the most reliable, but requires an API key and a hosted instance of unstructured and can't be used with local mode. See the unstructured.io documentation for more details: https://unstructured-io.github.io/unstructured/core/partition.html#partition-pdf"""


class UnstructuredDocumentFormat(BaseModel):
    r"""Extract text from document formats (.pdf, .docx, .md, .pptx) and emit as one record per file."""

    FILETYPE: Annotated[
        Annotated[
            Optional[SourceAzureBlobStorageSchemasStreamsFormatFiletype],
            AfterValidator(
                validate_const(
                    SourceAzureBlobStorageSchemasStreamsFormatFiletype.UNSTRUCTURED
                )
            ),
        ],
        pydantic.Field(alias="filetype"),
    ] = SourceAzureBlobStorageSchemasStreamsFormatFiletype.UNSTRUCTURED

    processing: Optional[Processing] = None
    r"""Processing configuration"""

    skip_unprocessable_files: Optional[bool] = True
    r"""If true, skip files that cannot be parsed and pass the error message along as the _ab_source_file_parse_error field. If false, fail the sync."""

    strategy: Optional[ParsingStrategy] = ParsingStrategy.AUTO
    r"""The strategy used to parse documents. `fast` extracts text directly from the document which doesn't work for all files. `ocr_only` is more reliable, but slower. `hi_res` is the most reliable, but requires an API key and a hosted instance of unstructured and can't be used with local mode. See the unstructured.io documentation for more details: https://unstructured-io.github.io/unstructured/core/partition.html#partition-pdf"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["filetype", "processing", "skip_unprocessable_files", "strategy"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceAzureBlobStorageSchemasStreamsFiletype(str, Enum):
    PARQUET = "parquet"


class ParquetFormatTypedDict(TypedDict):
    decimal_as_float: NotRequired[bool]
    r"""Whether to convert decimal fields to floats. There is a loss of precision when converting decimals to floats, so this is not recommended."""
    filetype: SourceAzureBlobStorageSchemasStreamsFiletype


class ParquetFormat(BaseModel):
    decimal_as_float: Optional[bool] = False
    r"""Whether to convert decimal fields to floats. There is a loss of precision when converting decimals to floats, so this is not recommended."""

    FILETYPE: Annotated[
        Annotated[
            Optional[SourceAzureBlobStorageSchemasStreamsFiletype],
            AfterValidator(
                validate_const(SourceAzureBlobStorageSchemasStreamsFiletype.PARQUET)
            ),
        ],
        pydantic.Field(alias="filetype"),
    ] = SourceAzureBlobStorageSchemasStreamsFiletype.PARQUET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["decimal_as_float", "filetype"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceAzureBlobStorageSchemasFiletype(str, Enum):
    JSONL = "jsonl"


class JsonlFormatTypedDict(TypedDict):
    filetype: SourceAzureBlobStorageSchemasFiletype


class JsonlFormat(BaseModel):
    FILETYPE: Annotated[
        Annotated[
            Optional[SourceAzureBlobStorageSchemasFiletype],
            AfterValidator(validate_const(SourceAzureBlobStorageSchemasFiletype.JSONL)),
        ],
        pydantic.Field(alias="filetype"),
    ] = SourceAzureBlobStorageSchemasFiletype.JSONL

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["filetype"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceAzureBlobStorageFiletype(str, Enum):
    CSV = "csv"


class SourceAzureBlobStorageSchemasHeaderDefinitionType(str, Enum):
    USER_PROVIDED = "User Provided"


class UserProvidedTypedDict(TypedDict):
    column_names: List[str]
    r"""The column names that will be used while emitting the CSV records"""
    header_definition_type: SourceAzureBlobStorageSchemasHeaderDefinitionType


class UserProvided(BaseModel):
    column_names: List[str]
    r"""The column names that will be used while emitting the CSV records"""

    HEADER_DEFINITION_TYPE: Annotated[
        Annotated[
            Optional[SourceAzureBlobStorageSchemasHeaderDefinitionType],
            AfterValidator(
                validate_const(
                    SourceAzureBlobStorageSchemasHeaderDefinitionType.USER_PROVIDED
                )
            ),
        ],
        pydantic.Field(alias="header_definition_type"),
    ] = SourceAzureBlobStorageSchemasHeaderDefinitionType.USER_PROVIDED

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["header_definition_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceAzureBlobStorageHeaderDefinitionType(str, Enum):
    AUTOGENERATED = "Autogenerated"


class AutogeneratedTypedDict(TypedDict):
    header_definition_type: SourceAzureBlobStorageHeaderDefinitionType


class Autogenerated(BaseModel):
    HEADER_DEFINITION_TYPE: Annotated[
        Annotated[
            Optional[SourceAzureBlobStorageHeaderDefinitionType],
            AfterValidator(
                validate_const(SourceAzureBlobStorageHeaderDefinitionType.AUTOGENERATED)
            ),
        ],
        pydantic.Field(alias="header_definition_type"),
    ] = SourceAzureBlobStorageHeaderDefinitionType.AUTOGENERATED

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["header_definition_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class HeaderDefinitionType(str, Enum):
    FROM_CSV = "From CSV"


class FromCSVTypedDict(TypedDict):
    header_definition_type: HeaderDefinitionType


class FromCSV(BaseModel):
    HEADER_DEFINITION_TYPE: Annotated[
        Annotated[
            Optional[HeaderDefinitionType],
            AfterValidator(validate_const(HeaderDefinitionType.FROM_CSV)),
        ],
        pydantic.Field(alias="header_definition_type"),
    ] = HeaderDefinitionType.FROM_CSV

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["header_definition_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


CSVHeaderDefinitionTypedDict = TypeAliasType(
    "CSVHeaderDefinitionTypedDict",
    Union[FromCSVTypedDict, AutogeneratedTypedDict, UserProvidedTypedDict],
)
r"""How headers will be defined. `User Provided` assumes the CSV does not have a header row and uses the headers provided and `Autogenerated` assumes the CSV does not have a header row and the CDK will generate headers using for `f{i}` where `i` is the index starting from 0. Else, the default behavior is to use the header from the CSV file. If a user wants to autogenerate or provide column names for a CSV having headers, they can skip rows."""


CSVHeaderDefinition = TypeAliasType(
    "CSVHeaderDefinition", Union[FromCSV, Autogenerated, UserProvided]
)
r"""How headers will be defined. `User Provided` assumes the CSV does not have a header row and uses the headers provided and `Autogenerated` assumes the CSV does not have a header row and the CDK will generate headers using for `f{i}` where `i` is the index starting from 0. Else, the default behavior is to use the header from the CSV file. If a user wants to autogenerate or provide column names for a CSV having headers, they can skip rows."""


class CSVFormatTypedDict(TypedDict):
    delimiter: NotRequired[str]
    r"""The character delimiting individual cells in the CSV data. This may only be a 1-character string. For tab-delimited data enter '\t'."""
    double_quote: NotRequired[bool]
    r"""Whether two quotes in a quoted CSV value denote a single quote in the data."""
    encoding: NotRequired[str]
    r"""The character encoding of the CSV data. Leave blank to default to <strong>UTF8</strong>. See <a href=\"https://docs.python.org/3/library/codecs.html#standard-encodings\" target=\"_blank\">list of python encodings</a> for allowable options."""
    escape_char: NotRequired[str]
    r"""The character used for escaping special characters. To disallow escaping, leave this field blank."""
    false_values: NotRequired[List[str]]
    r"""A set of case-sensitive strings that should be interpreted as false values."""
    filetype: SourceAzureBlobStorageFiletype
    header_definition: NotRequired[CSVHeaderDefinitionTypedDict]
    r"""How headers will be defined. `User Provided` assumes the CSV does not have a header row and uses the headers provided and `Autogenerated` assumes the CSV does not have a header row and the CDK will generate headers using for `f{i}` where `i` is the index starting from 0. Else, the default behavior is to use the header from the CSV file. If a user wants to autogenerate or provide column names for a CSV having headers, they can skip rows."""
    ignore_errors_on_fields_mismatch: NotRequired[bool]
    r"""Whether to ignore errors that occur when the number of fields in the CSV does not match the number of columns in the schema."""
    null_values: NotRequired[List[str]]
    r"""A set of case-sensitive strings that should be interpreted as null values. For example, if the value 'NA' should be interpreted as null, enter 'NA' in this field."""
    quote_char: NotRequired[str]
    r"""The character used for quoting CSV values. To disallow quoting, make this field blank."""
    skip_rows_after_header: NotRequired[int]
    r"""The number of rows to skip after the header row."""
    skip_rows_before_header: NotRequired[int]
    r"""The number of rows to skip before the header row. For example, if the header row is on the 3rd row, enter 2 in this field."""
    strings_can_be_null: NotRequired[bool]
    r"""Whether strings can be interpreted as null values. If true, strings that match the null_values set will be interpreted as null. If false, strings that match the null_values set will be interpreted as the string itself."""
    true_values: NotRequired[List[str]]
    r"""A set of case-sensitive strings that should be interpreted as true values."""


class CSVFormat(BaseModel):
    delimiter: Optional[str] = ","
    r"""The character delimiting individual cells in the CSV data. This may only be a 1-character string. For tab-delimited data enter '\t'."""

    double_quote: Optional[bool] = True
    r"""Whether two quotes in a quoted CSV value denote a single quote in the data."""

    encoding: Optional[str] = "utf8"
    r"""The character encoding of the CSV data. Leave blank to default to <strong>UTF8</strong>. See <a href=\"https://docs.python.org/3/library/codecs.html#standard-encodings\" target=\"_blank\">list of python encodings</a> for allowable options."""

    escape_char: Optional[str] = None
    r"""The character used for escaping special characters. To disallow escaping, leave this field blank."""

    false_values: Optional[List[str]] = None
    r"""A set of case-sensitive strings that should be interpreted as false values."""

    FILETYPE: Annotated[
        Annotated[
            Optional[SourceAzureBlobStorageFiletype],
            AfterValidator(validate_const(SourceAzureBlobStorageFiletype.CSV)),
        ],
        pydantic.Field(alias="filetype"),
    ] = SourceAzureBlobStorageFiletype.CSV

    header_definition: Optional[CSVHeaderDefinition] = None
    r"""How headers will be defined. `User Provided` assumes the CSV does not have a header row and uses the headers provided and `Autogenerated` assumes the CSV does not have a header row and the CDK will generate headers using for `f{i}` where `i` is the index starting from 0. Else, the default behavior is to use the header from the CSV file. If a user wants to autogenerate or provide column names for a CSV having headers, they can skip rows."""

    ignore_errors_on_fields_mismatch: Optional[bool] = False
    r"""Whether to ignore errors that occur when the number of fields in the CSV does not match the number of columns in the schema."""

    null_values: Optional[List[str]] = None
    r"""A set of case-sensitive strings that should be interpreted as null values. For example, if the value 'NA' should be interpreted as null, enter 'NA' in this field."""

    quote_char: Optional[str] = '"'
    r"""The character used for quoting CSV values. To disallow quoting, make this field blank."""

    skip_rows_after_header: Optional[int] = 0
    r"""The number of rows to skip after the header row."""

    skip_rows_before_header: Optional[int] = 0
    r"""The number of rows to skip before the header row. For example, if the header row is on the 3rd row, enter 2 in this field."""

    strings_can_be_null: Optional[bool] = True
    r"""Whether strings can be interpreted as null values. If true, strings that match the null_values set will be interpreted as null. If false, strings that match the null_values set will be interpreted as the string itself."""

    true_values: Optional[List[str]] = None
    r"""A set of case-sensitive strings that should be interpreted as true values."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "delimiter",
                "double_quote",
                "encoding",
                "escape_char",
                "false_values",
                "filetype",
                "header_definition",
                "ignore_errors_on_fields_mismatch",
                "null_values",
                "quote_char",
                "skip_rows_after_header",
                "skip_rows_before_header",
                "strings_can_be_null",
                "true_values",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class Filetype(str, Enum):
    AVRO = "avro"


class AvroFormatTypedDict(TypedDict):
    double_as_string: NotRequired[bool]
    r"""Whether to convert double fields to strings. This is recommended if you have decimal numbers with a high degree of precision because there can be a loss precision when handling floating point numbers."""
    filetype: Filetype


class AvroFormat(BaseModel):
    double_as_string: Optional[bool] = False
    r"""Whether to convert double fields to strings. This is recommended if you have decimal numbers with a high degree of precision because there can be a loss precision when handling floating point numbers."""

    FILETYPE: Annotated[
        Annotated[Optional[Filetype], AfterValidator(validate_const(Filetype.AVRO))],
        pydantic.Field(alias="filetype"),
    ] = Filetype.AVRO

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["double_as_string", "filetype"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


FormatTypedDict = TypeAliasType(
    "FormatTypedDict",
    Union[
        JsonlFormatTypedDict,
        ExcelFormatTypedDict,
        AvroFormatTypedDict,
        ParquetFormatTypedDict,
        UnstructuredDocumentFormatTypedDict,
        CSVFormatTypedDict,
    ],
)
r"""The configuration options that are used to alter how to read incoming files that deviate from the standard formatting."""


Format = TypeAliasType(
    "Format",
    Union[
        JsonlFormat,
        ExcelFormat,
        AvroFormat,
        ParquetFormat,
        UnstructuredDocumentFormat,
        CSVFormat,
    ],
)
r"""The configuration options that are used to alter how to read incoming files that deviate from the standard formatting."""


class ValidationPolicy(str, Enum):
    r"""The name of the validation policy that dictates sync behavior when a record does not adhere to the stream schema."""

    EMIT_RECORD = "Emit Record"
    SKIP_RECORD = "Skip Record"
    WAIT_FOR_DISCOVER = "Wait for Discover"


class FileBasedStreamConfigTypedDict(TypedDict):
    format_: FormatTypedDict
    r"""The configuration options that are used to alter how to read incoming files that deviate from the standard formatting."""
    name: str
    r"""The name of the stream."""
    days_to_sync_if_history_is_full: NotRequired[int]
    r"""When the state history of the file store is full, syncs will only read files that were last modified in the provided day range."""
    globs: NotRequired[List[str]]
    r"""The pattern used to specify which files should be selected from the file system. For more information on glob pattern matching look <a href=\"https://en.wikipedia.org/wiki/Glob_(programming)\">here</a>."""
    input_schema: NotRequired[str]
    r"""The schema that will be used to validate records extracted from the file. This will override the stream schema that is auto-detected from incoming files."""
    recent_n_files_to_read_for_schema_discovery: NotRequired[int]
    r"""The number of resent files which will be used to discover the schema for this stream."""
    schemaless: NotRequired[bool]
    r"""When enabled, syncs will not validate or structure records against the stream's schema."""
    validation_policy: NotRequired[ValidationPolicy]
    r"""The name of the validation policy that dictates sync behavior when a record does not adhere to the stream schema."""


class FileBasedStreamConfig(BaseModel):
    format_: Annotated[Format, pydantic.Field(alias="format")]
    r"""The configuration options that are used to alter how to read incoming files that deviate from the standard formatting."""

    name: str
    r"""The name of the stream."""

    days_to_sync_if_history_is_full: Optional[int] = 3
    r"""When the state history of the file store is full, syncs will only read files that were last modified in the provided day range."""

    globs: Optional[List[str]] = None
    r"""The pattern used to specify which files should be selected from the file system. For more information on glob pattern matching look <a href=\"https://en.wikipedia.org/wiki/Glob_(programming)\">here</a>."""

    input_schema: Optional[str] = None
    r"""The schema that will be used to validate records extracted from the file. This will override the stream schema that is auto-detected from incoming files."""

    recent_n_files_to_read_for_schema_discovery: Optional[int] = None
    r"""The number of resent files which will be used to discover the schema for this stream."""

    schemaless: Optional[bool] = False
    r"""When enabled, syncs will not validate or structure records against the stream's schema."""

    validation_policy: Optional[ValidationPolicy] = ValidationPolicy.EMIT_RECORD
    r"""The name of the validation policy that dictates sync behavior when a record does not adhere to the stream schema."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "days_to_sync_if_history_is_full",
                "globs",
                "input_schema",
                "recent_n_files_to_read_for_schema_discovery",
                "schemaless",
                "validation_policy",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceAzureBlobStorageTypedDict(TypedDict):
    r"""NOTE: When this Spec is changed, legacy_config_transformer.py must also be modified to uptake the changes
    because it is responsible for converting legacy Azure Blob Storage v0 configs into v1 configs using the File-Based CDK.
    """

    azure_blob_storage_account_name: str
    r"""The account's name of the Azure Blob Storage."""
    azure_blob_storage_container_name: str
    r"""The name of the Azure blob storage container."""
    credentials: SourceAzureBlobStorageAuthenticationTypedDict
    r"""Credentials for connecting to the Azure Blob Storage"""
    streams: List[FileBasedStreamConfigTypedDict]
    r"""Each instance of this configuration defines a <a href=\"https://docs.airbyte.com/cloud/core-concepts#stream\">stream</a>. Use this to define which files belong in the stream, their format, and how they should be parsed and validated. When sending data to warehouse destination such as Snowflake or BigQuery, each stream is a separate table."""
    azure_blob_storage_endpoint: NotRequired[str]
    r"""This is Azure Blob Storage endpoint domain name. Leave default value (or leave it empty if run container from command line) to use Microsoft native from example."""
    source_type: SourceAzureBlobStorageAzureBlobStorage
    start_date: NotRequired[datetime]
    r"""UTC date and time in the format 2017-01-25T00:00:00.000000Z. Any file modified before this date will not be replicated."""


class SourceAzureBlobStorage(BaseModel):
    r"""NOTE: When this Spec is changed, legacy_config_transformer.py must also be modified to uptake the changes
    because it is responsible for converting legacy Azure Blob Storage v0 configs into v1 configs using the File-Based CDK.
    """

    azure_blob_storage_account_name: str
    r"""The account's name of the Azure Blob Storage."""

    azure_blob_storage_container_name: str
    r"""The name of the Azure blob storage container."""

    credentials: SourceAzureBlobStorageAuthentication
    r"""Credentials for connecting to the Azure Blob Storage"""

    streams: List[FileBasedStreamConfig]
    r"""Each instance of this configuration defines a <a href=\"https://docs.airbyte.com/cloud/core-concepts#stream\">stream</a>. Use this to define which files belong in the stream, their format, and how they should be parsed and validated. When sending data to warehouse destination such as Snowflake or BigQuery, each stream is a separate table."""

    azure_blob_storage_endpoint: Optional[str] = None
    r"""This is Azure Blob Storage endpoint domain name. Leave default value (or leave it empty if run container from command line) to use Microsoft native from example."""

    SOURCE_TYPE: Annotated[
        Annotated[
            SourceAzureBlobStorageAzureBlobStorage,
            AfterValidator(
                validate_const(
                    SourceAzureBlobStorageAzureBlobStorage.AZURE_BLOB_STORAGE
                )
            ),
        ],
        pydantic.Field(alias="sourceType"),
    ] = SourceAzureBlobStorageAzureBlobStorage.AZURE_BLOB_STORAGE

    start_date: Optional[datetime] = None
    r"""UTC date and time in the format 2017-01-25T00:00:00.000000Z. Any file modified before this date will not be replicated."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["azure_blob_storage_endpoint", "start_date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AuthenticateViaStorageAccountKey.model_rebuild()
except NameError:
    pass
try:
    AuthenticateViaClientCredentials.model_rebuild()
except NameError:
    pass
try:
    AuthenticateViaOauth2.model_rebuild()
except NameError:
    pass
try:
    ExcelFormat.model_rebuild()
except NameError:
    pass
try:
    Local.model_rebuild()
except NameError:
    pass
try:
    UnstructuredDocumentFormat.model_rebuild()
except NameError:
    pass
try:
    ParquetFormat.model_rebuild()
except NameError:
    pass
try:
    JsonlFormat.model_rebuild()
except NameError:
    pass
try:
    UserProvided.model_rebuild()
except NameError:
    pass
try:
    Autogenerated.model_rebuild()
except NameError:
    pass
try:
    FromCSV.model_rebuild()
except NameError:
    pass
try:
    CSVFormat.model_rebuild()
except NameError:
    pass
try:
    AvroFormat.model_rebuild()
except NameError:
    pass
try:
    FileBasedStreamConfig.model_rebuild()
except NameError:
    pass
try:
    SourceAzureBlobStorage.model_rebuild()
except NameError:
    pass
