"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel, UNSET_SENTINEL
from airbyte_api.utils import get_discriminator, validate_const
from enum import Enum
import pydantic
from pydantic import Discriminator, Tag, model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class AuthenticationMethodOauth2AccessToken(str, Enum):
    OAUTH2_ACCESS_TOKEN = "oauth2_access_token"


class OAuth2AccessTokenTypedDict(TypedDict):
    access_token: str
    r"""Also called <a href=\"https://auth0.com/docs/secure/tokens/access-tokens/get-management-api-access-tokens-for-testing\">API Access Token </a> The access token used to call the Auth0 Management API Token. It's a JWT that contains specific grant permissions knowns as scopes."""
    auth_type: AuthenticationMethodOauth2AccessToken


class OAuth2AccessToken(BaseModel):
    access_token: str
    r"""Also called <a href=\"https://auth0.com/docs/secure/tokens/access-tokens/get-management-api-access-tokens-for-testing\">API Access Token </a> The access token used to call the Auth0 Management API Token. It's a JWT that contains specific grant permissions knowns as scopes."""

    AUTH_TYPE: Annotated[
        Annotated[
            AuthenticationMethodOauth2AccessToken,
            AfterValidator(
                validate_const(
                    AuthenticationMethodOauth2AccessToken.OAUTH2_ACCESS_TOKEN
                )
            ),
        ],
        pydantic.Field(alias="auth_type"),
    ] = AuthenticationMethodOauth2AccessToken.OAUTH2_ACCESS_TOKEN


class AuthenticationMethodOauth2ConfidentialApplication(str, Enum):
    OAUTH2_CONFIDENTIAL_APPLICATION = "oauth2_confidential_application"


class OAuth2ConfidentialApplicationTypedDict(TypedDict):
    audience: str
    r"""The audience for the token, which is your API. You can find this in the Identifier field on your  <a href=\"https://manage.auth0.com/#/apis\">API's settings tab</a>"""
    client_id: str
    r"""Your application's Client ID. You can find this value on the <a href=\"https://manage.auth0.com/#/applications\">application's settings tab</a> after you login the admin portal."""
    client_secret: str
    r"""Your application's Client Secret. You can find this value on the <a href=\"https://manage.auth0.com/#/applications\">application's settings tab</a> after you login the admin portal."""
    auth_type: AuthenticationMethodOauth2ConfidentialApplication


class OAuth2ConfidentialApplication(BaseModel):
    audience: str
    r"""The audience for the token, which is your API. You can find this in the Identifier field on your  <a href=\"https://manage.auth0.com/#/apis\">API's settings tab</a>"""

    client_id: str
    r"""Your application's Client ID. You can find this value on the <a href=\"https://manage.auth0.com/#/applications\">application's settings tab</a> after you login the admin portal."""

    client_secret: str
    r"""Your application's Client Secret. You can find this value on the <a href=\"https://manage.auth0.com/#/applications\">application's settings tab</a> after you login the admin portal."""

    AUTH_TYPE: Annotated[
        Annotated[
            AuthenticationMethodOauth2ConfidentialApplication,
            AfterValidator(
                validate_const(
                    AuthenticationMethodOauth2ConfidentialApplication.OAUTH2_CONFIDENTIAL_APPLICATION
                )
            ),
        ],
        pydantic.Field(alias="auth_type"),
    ] = AuthenticationMethodOauth2ConfidentialApplication.OAUTH2_CONFIDENTIAL_APPLICATION


SourceAuth0AuthenticationMethodUnionTypedDict = TypeAliasType(
    "SourceAuth0AuthenticationMethodUnionTypedDict",
    Union[OAuth2AccessTokenTypedDict, OAuth2ConfidentialApplicationTypedDict],
)


SourceAuth0AuthenticationMethodUnion = Annotated[
    Union[
        Annotated[
            OAuth2ConfidentialApplication, Tag("oauth2_confidential_application")
        ],
        Annotated[OAuth2AccessToken, Tag("oauth2_access_token")],
    ],
    Discriminator(lambda m: get_discriminator(m, "auth_type", "auth_type")),
]


class Auth0(str, Enum):
    AUTH0 = "auth0"


class SourceAuth0TypedDict(TypedDict):
    base_url: str
    r"""The Authentication API is served over HTTPS. All URLs referenced in the documentation have the following base `https://YOUR_DOMAIN`"""
    credentials: SourceAuth0AuthenticationMethodUnionTypedDict
    source_type: Auth0
    start_date: NotRequired[str]
    r"""UTC date and time in the format 2017-01-25T00:00:00Z. Any data before this date will not be replicated."""


class SourceAuth0(BaseModel):
    base_url: str
    r"""The Authentication API is served over HTTPS. All URLs referenced in the documentation have the following base `https://YOUR_DOMAIN`"""

    credentials: SourceAuth0AuthenticationMethodUnion

    SOURCE_TYPE: Annotated[
        Annotated[Auth0, AfterValidator(validate_const(Auth0.AUTH0))],
        pydantic.Field(alias="sourceType"),
    ] = Auth0.AUTH0

    start_date: Optional[str] = "2023-08-05T00:43:59.244Z"
    r"""UTC date and time in the format 2017-01-25T00:00:00Z. Any data before this date will not be replicated."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["start_date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    OAuth2AccessToken.model_rebuild()
except NameError:
    pass
try:
    OAuth2ConfidentialApplication.model_rebuild()
except NameError:
    pass
try:
    SourceAuth0.model_rebuild()
except NameError:
    pass
