"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel, UNSET_SENTINEL
from airbyte_api.utils import get_discriminator, validate_const
from enum import Enum
import pydantic
from pydantic import Discriminator, Tag, model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class SourceOracleConnectionType(str, Enum):
    SID = "sid"


class SystemIDSIDTypedDict(TypedDict):
    r"""Use SID (Oracle System Identifier)"""

    sid: str
    connection_type: SourceOracleConnectionType


class SystemIDSID(BaseModel):
    r"""Use SID (Oracle System Identifier)"""

    sid: str

    CONNECTION_TYPE: Annotated[
        Annotated[
            Optional[SourceOracleConnectionType],
            AfterValidator(validate_const(SourceOracleConnectionType.SID)),
        ],
        pydantic.Field(alias="connection_type"),
    ] = SourceOracleConnectionType.SID

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["connection_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ConnectionType(str, Enum):
    SERVICE_NAME = "service_name"


class ServiceNameTypedDict(TypedDict):
    r"""Use service name"""

    service_name: str
    connection_type: ConnectionType


class ServiceName(BaseModel):
    r"""Use service name"""

    service_name: str

    CONNECTION_TYPE: Annotated[
        Annotated[
            Optional[ConnectionType],
            AfterValidator(validate_const(ConnectionType.SERVICE_NAME)),
        ],
        pydantic.Field(alias="connection_type"),
    ] = ConnectionType.SERVICE_NAME

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["connection_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ConnectByTypedDict = TypeAliasType(
    "ConnectByTypedDict", Union[ServiceNameTypedDict, SystemIDSIDTypedDict]
)
r"""Connect data that will be used for DB connection"""


ConnectBy = TypeAliasType("ConnectBy", Union[ServiceName, SystemIDSID])
r"""Connect data that will be used for DB connection"""


class SourceOracleSchemasEncryptionEncryptionMethod(str, Enum):
    ENCRYPTED_VERIFY_CERTIFICATE = "encrypted_verify_certificate"


class SourceOracleTLSEncryptedVerifyCertificateTypedDict(TypedDict):
    r"""Verify and use the certificate provided by the server."""

    ssl_certificate: str
    r"""Privacy Enhanced Mail (PEM) files are concatenated certificate containers frequently used in certificate installations."""
    encryption_method: SourceOracleSchemasEncryptionEncryptionMethod


class SourceOracleTLSEncryptedVerifyCertificate(BaseModel):
    r"""Verify and use the certificate provided by the server."""

    ssl_certificate: str
    r"""Privacy Enhanced Mail (PEM) files are concatenated certificate containers frequently used in certificate installations."""

    ENCRYPTION_METHOD: Annotated[
        Annotated[
            SourceOracleSchemasEncryptionEncryptionMethod,
            AfterValidator(
                validate_const(
                    SourceOracleSchemasEncryptionEncryptionMethod.ENCRYPTED_VERIFY_CERTIFICATE
                )
            ),
        ],
        pydantic.Field(alias="encryption_method"),
    ] = SourceOracleSchemasEncryptionEncryptionMethod.ENCRYPTED_VERIFY_CERTIFICATE


class SourceOracleEncryptionAlgorithm(str, Enum):
    r"""This parameter defines what encryption algorithm is used."""

    AES256 = "AES256"
    RC4_56 = "RC4_56"
    THREE_DES168 = "3DES168"


class SourceOracleSchemasEncryptionMethod(str, Enum):
    CLIENT_NNE = "client_nne"


class SourceOracleNativeNetworkEncryptionNNETypedDict(TypedDict):
    r"""The native network encryption gives you the ability to encrypt database connections, without the configuration overhead of TCP/IP and SSL/TLS and without the need to open and listen on different ports."""

    encryption_algorithm: NotRequired[SourceOracleEncryptionAlgorithm]
    r"""This parameter defines what encryption algorithm is used."""
    encryption_method: SourceOracleSchemasEncryptionMethod


class SourceOracleNativeNetworkEncryptionNNE(BaseModel):
    r"""The native network encryption gives you the ability to encrypt database connections, without the configuration overhead of TCP/IP and SSL/TLS and without the need to open and listen on different ports."""

    encryption_algorithm: Optional[SourceOracleEncryptionAlgorithm] = (
        SourceOracleEncryptionAlgorithm.AES256
    )
    r"""This parameter defines what encryption algorithm is used."""

    ENCRYPTION_METHOD: Annotated[
        Annotated[
            SourceOracleSchemasEncryptionMethod,
            AfterValidator(
                validate_const(SourceOracleSchemasEncryptionMethod.CLIENT_NNE)
            ),
        ],
        pydantic.Field(alias="encryption_method"),
    ] = SourceOracleSchemasEncryptionMethod.CLIENT_NNE

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["encryption_algorithm"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceOracleEncryptionMethod(str, Enum):
    UNENCRYPTED = "unencrypted"


class SourceOracleUnencryptedTypedDict(TypedDict):
    r"""Data transfer will not be encrypted."""

    encryption_method: SourceOracleEncryptionMethod


class SourceOracleUnencrypted(BaseModel):
    r"""Data transfer will not be encrypted."""

    ENCRYPTION_METHOD: Annotated[
        Annotated[
            SourceOracleEncryptionMethod,
            AfterValidator(validate_const(SourceOracleEncryptionMethod.UNENCRYPTED)),
        ],
        pydantic.Field(alias="encryption_method"),
    ] = SourceOracleEncryptionMethod.UNENCRYPTED


SourceOracleEncryptionTypedDict = TypeAliasType(
    "SourceOracleEncryptionTypedDict",
    Union[
        SourceOracleUnencryptedTypedDict,
        SourceOracleNativeNetworkEncryptionNNETypedDict,
        SourceOracleTLSEncryptedVerifyCertificateTypedDict,
    ],
)
r"""The encryption method with is used when communicating with the database."""


SourceOracleEncryption = Annotated[
    Union[
        Annotated[SourceOracleUnencrypted, Tag("unencrypted")],
        Annotated[SourceOracleNativeNetworkEncryptionNNE, Tag("client_nne")],
        Annotated[
            SourceOracleTLSEncryptedVerifyCertificate,
            Tag("encrypted_verify_certificate"),
        ],
    ],
    Discriminator(
        lambda m: get_discriminator(m, "encryption_method", "encryption_method")
    ),
]
r"""The encryption method with is used when communicating with the database."""


class SourceOracleOracle(str, Enum):
    ORACLE = "oracle"


class SourceOracleSchemasTunnelMethodTunnelMethod(str, Enum):
    r"""Connect through a jump server tunnel host using username and password authentication"""

    SSH_PASSWORD_AUTH = "SSH_PASSWORD_AUTH"


class SourceOraclePasswordAuthenticationTypedDict(TypedDict):
    tunnel_host: str
    r"""Hostname of the jump server host that allows inbound ssh tunnel."""
    tunnel_user: str
    r"""OS-level username for logging into the jump server host"""
    tunnel_user_password: str
    r"""OS-level password for logging into the jump server host"""
    tunnel_method: SourceOracleSchemasTunnelMethodTunnelMethod
    r"""Connect through a jump server tunnel host using username and password authentication"""
    tunnel_port: NotRequired[int]
    r"""Port on the proxy/jump server that accepts inbound ssh connections."""


class SourceOraclePasswordAuthentication(BaseModel):
    tunnel_host: str
    r"""Hostname of the jump server host that allows inbound ssh tunnel."""

    tunnel_user: str
    r"""OS-level username for logging into the jump server host"""

    tunnel_user_password: str
    r"""OS-level password for logging into the jump server host"""

    TUNNEL_METHOD: Annotated[
        Annotated[
            SourceOracleSchemasTunnelMethodTunnelMethod,
            AfterValidator(
                validate_const(
                    SourceOracleSchemasTunnelMethodTunnelMethod.SSH_PASSWORD_AUTH
                )
            ),
        ],
        pydantic.Field(alias="tunnel_method"),
    ] = SourceOracleSchemasTunnelMethodTunnelMethod.SSH_PASSWORD_AUTH
    r"""Connect through a jump server tunnel host using username and password authentication"""

    tunnel_port: Optional[int] = 22
    r"""Port on the proxy/jump server that accepts inbound ssh connections."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["tunnel_port"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceOracleSchemasTunnelMethod(str, Enum):
    r"""Connect through a jump server tunnel host using username and ssh key"""

    SSH_KEY_AUTH = "SSH_KEY_AUTH"


class SourceOracleSSHKeyAuthenticationTypedDict(TypedDict):
    ssh_key: str
    r"""OS-level user account ssh key credentials in RSA PEM format ( created with ssh-keygen -t rsa -m PEM -f myuser_rsa )"""
    tunnel_host: str
    r"""Hostname of the jump server host that allows inbound ssh tunnel."""
    tunnel_user: str
    r"""OS-level username for logging into the jump server host."""
    tunnel_method: SourceOracleSchemasTunnelMethod
    r"""Connect through a jump server tunnel host using username and ssh key"""
    tunnel_port: NotRequired[int]
    r"""Port on the proxy/jump server that accepts inbound ssh connections."""


class SourceOracleSSHKeyAuthentication(BaseModel):
    ssh_key: str
    r"""OS-level user account ssh key credentials in RSA PEM format ( created with ssh-keygen -t rsa -m PEM -f myuser_rsa )"""

    tunnel_host: str
    r"""Hostname of the jump server host that allows inbound ssh tunnel."""

    tunnel_user: str
    r"""OS-level username for logging into the jump server host."""

    TUNNEL_METHOD: Annotated[
        Annotated[
            SourceOracleSchemasTunnelMethod,
            AfterValidator(
                validate_const(SourceOracleSchemasTunnelMethod.SSH_KEY_AUTH)
            ),
        ],
        pydantic.Field(alias="tunnel_method"),
    ] = SourceOracleSchemasTunnelMethod.SSH_KEY_AUTH
    r"""Connect through a jump server tunnel host using username and ssh key"""

    tunnel_port: Optional[int] = 22
    r"""Port on the proxy/jump server that accepts inbound ssh connections."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["tunnel_port"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceOracleTunnelMethod(str, Enum):
    r"""No ssh tunnel needed to connect to database"""

    NO_TUNNEL = "NO_TUNNEL"


class SourceOracleNoTunnelTypedDict(TypedDict):
    tunnel_method: SourceOracleTunnelMethod
    r"""No ssh tunnel needed to connect to database"""


class SourceOracleNoTunnel(BaseModel):
    TUNNEL_METHOD: Annotated[
        Annotated[
            SourceOracleTunnelMethod,
            AfterValidator(validate_const(SourceOracleTunnelMethod.NO_TUNNEL)),
        ],
        pydantic.Field(alias="tunnel_method"),
    ] = SourceOracleTunnelMethod.NO_TUNNEL
    r"""No ssh tunnel needed to connect to database"""


SourceOracleSSHTunnelMethodTypedDict = TypeAliasType(
    "SourceOracleSSHTunnelMethodTypedDict",
    Union[
        SourceOracleNoTunnelTypedDict,
        SourceOracleSSHKeyAuthenticationTypedDict,
        SourceOraclePasswordAuthenticationTypedDict,
    ],
)
r"""Whether to initiate an SSH tunnel before connecting to the database, and if so, which kind of authentication to use."""


SourceOracleSSHTunnelMethod = Annotated[
    Union[
        Annotated[SourceOracleNoTunnel, Tag("NO_TUNNEL")],
        Annotated[SourceOracleSSHKeyAuthentication, Tag("SSH_KEY_AUTH")],
        Annotated[SourceOraclePasswordAuthentication, Tag("SSH_PASSWORD_AUTH")],
    ],
    Discriminator(lambda m: get_discriminator(m, "tunnel_method", "tunnel_method")),
]
r"""Whether to initiate an SSH tunnel before connecting to the database, and if so, which kind of authentication to use."""


class SourceOracleTypedDict(TypedDict):
    host: str
    r"""Hostname of the database."""
    username: str
    r"""The username which is used to access the database."""
    connection_data: NotRequired[ConnectByTypedDict]
    r"""Connect data that will be used for DB connection"""
    encryption: NotRequired[SourceOracleEncryptionTypedDict]
    r"""The encryption method with is used when communicating with the database."""
    jdbc_url_params: NotRequired[str]
    r"""Additional properties to pass to the JDBC URL string when connecting to the database formatted as 'key=value' pairs separated by the symbol '&'. (example: key1=value1&key2=value2&key3=value3)."""
    password: NotRequired[str]
    r"""The password associated with the username."""
    port: NotRequired[int]
    r"""Port of the database.
    Oracle Corporations recommends the following port numbers:
    1521 - Default listening port for client connections to the listener.
    2484 - Recommended and officially registered listening port for client connections to the listener using TCP/IP with SSL
    """
    schemas: NotRequired[List[str]]
    r"""The list of schemas to sync from. Defaults to user. Case sensitive."""
    source_type: SourceOracleOracle
    tunnel_method: NotRequired[SourceOracleSSHTunnelMethodTypedDict]
    r"""Whether to initiate an SSH tunnel before connecting to the database, and if so, which kind of authentication to use."""


class SourceOracle(BaseModel):
    host: str
    r"""Hostname of the database."""

    username: str
    r"""The username which is used to access the database."""

    connection_data: Optional[ConnectBy] = None
    r"""Connect data that will be used for DB connection"""

    encryption: Optional[SourceOracleEncryption] = None
    r"""The encryption method with is used when communicating with the database."""

    jdbc_url_params: Optional[str] = None
    r"""Additional properties to pass to the JDBC URL string when connecting to the database formatted as 'key=value' pairs separated by the symbol '&'. (example: key1=value1&key2=value2&key3=value3)."""

    password: Optional[str] = None
    r"""The password associated with the username."""

    port: Optional[int] = 1521
    r"""Port of the database.
    Oracle Corporations recommends the following port numbers:
    1521 - Default listening port for client connections to the listener.
    2484 - Recommended and officially registered listening port for client connections to the listener using TCP/IP with SSL
    """

    schemas: Optional[List[str]] = None
    r"""The list of schemas to sync from. Defaults to user. Case sensitive."""

    SOURCE_TYPE: Annotated[
        Annotated[
            SourceOracleOracle,
            AfterValidator(validate_const(SourceOracleOracle.ORACLE)),
        ],
        pydantic.Field(alias="sourceType"),
    ] = SourceOracleOracle.ORACLE

    tunnel_method: Optional[SourceOracleSSHTunnelMethod] = None
    r"""Whether to initiate an SSH tunnel before connecting to the database, and if so, which kind of authentication to use."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "connection_data",
                "encryption",
                "jdbc_url_params",
                "password",
                "port",
                "schemas",
                "tunnel_method",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SystemIDSID.model_rebuild()
except NameError:
    pass
try:
    ServiceName.model_rebuild()
except NameError:
    pass
try:
    SourceOracleTLSEncryptedVerifyCertificate.model_rebuild()
except NameError:
    pass
try:
    SourceOracleNativeNetworkEncryptionNNE.model_rebuild()
except NameError:
    pass
try:
    SourceOracleUnencrypted.model_rebuild()
except NameError:
    pass
try:
    SourceOraclePasswordAuthentication.model_rebuild()
except NameError:
    pass
try:
    SourceOracleSSHKeyAuthentication.model_rebuild()
except NameError:
    pass
try:
    SourceOracleNoTunnel.model_rebuild()
except NameError:
    pass
try:
    SourceOracle.model_rebuild()
except NameError:
    pass
