"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .connectionsyncmodeenum import ConnectionSyncModeEnum
from airbyte_api.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class StreamPropertiesTypedDict(TypedDict):
    r"""The stream properties associated with a connection."""

    default_cursor_field: NotRequired[List[str]]
    property_fields: NotRequired[List[List[str]]]
    source_defined_cursor_field: NotRequired[bool]
    source_defined_primary_key: NotRequired[List[List[str]]]
    stream_name: NotRequired[str]
    streamnamespace: NotRequired[str]
    sync_modes: NotRequired[List[ConnectionSyncModeEnum]]


class StreamProperties(BaseModel):
    r"""The stream properties associated with a connection."""

    default_cursor_field: Annotated[
        Optional[List[str]], pydantic.Field(alias="defaultCursorField")
    ] = None

    property_fields: Annotated[
        Optional[List[List[str]]], pydantic.Field(alias="propertyFields")
    ] = None

    source_defined_cursor_field: Annotated[
        Optional[bool], pydantic.Field(alias="sourceDefinedCursorField")
    ] = None

    source_defined_primary_key: Annotated[
        Optional[List[List[str]]], pydantic.Field(alias="sourceDefinedPrimaryKey")
    ] = None

    stream_name: Annotated[Optional[str], pydantic.Field(alias="streamName")] = None

    streamnamespace: Optional[str] = None

    sync_modes: Annotated[
        Optional[List[ConnectionSyncModeEnum]], pydantic.Field(alias="syncModes")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "defaultCursorField",
                "propertyFields",
                "sourceDefinedCursorField",
                "sourceDefinedPrimaryKey",
                "streamName",
                "streamnamespace",
                "syncModes",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    StreamProperties.model_rebuild()
except NameError:
    pass
