"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel
from typing_extensions import TypedDict


class TagPatchRequestTypedDict(TypedDict):
    color: str
    name: str


class TagPatchRequest(BaseModel):
    color: str

    name: str
