"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from airbyte_api.types import BaseModel, UNSET_SENTINEL
from airbyte_api.utils import get_discriminator, validate_const
from datetime import date
from enum import Enum
import pydantic
from pydantic import Discriminator, Tag, model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class SourceGoogleAnalyticsDataAPICredentialsCredentialsAuthType(str, Enum):
    SERVICE = "Service"


class CredentialsServiceAccountKeyAuthenticationTypedDict(TypedDict):
    credentials_json: str
    r"""The JSON key linked to the service account used for authorization. For steps on obtaining this key, refer to <a href=\"https://docs.airbyte.com/integrations/sources/google-analytics-data-api/#setup-guide\">the setup guide</a>."""
    auth_type: SourceGoogleAnalyticsDataAPICredentialsCredentialsAuthType


class CredentialsServiceAccountKeyAuthentication(BaseModel):
    credentials_json: str
    r"""The JSON key linked to the service account used for authorization. For steps on obtaining this key, refer to <a href=\"https://docs.airbyte.com/integrations/sources/google-analytics-data-api/#setup-guide\">the setup guide</a>."""

    AUTH_TYPE: Annotated[
        Annotated[
            Optional[SourceGoogleAnalyticsDataAPICredentialsCredentialsAuthType],
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPICredentialsCredentialsAuthType.SERVICE
                )
            ),
        ],
        pydantic.Field(alias="auth_type"),
    ] = SourceGoogleAnalyticsDataAPICredentialsCredentialsAuthType.SERVICE

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["auth_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceGoogleAnalyticsDataAPICredentialsAuthType(str, Enum):
    CLIENT = "Client"


class CredentialsAuthenticateViaGoogleOauthTypedDict(TypedDict):
    client_id: str
    r"""The Client ID of your Google Analytics developer application."""
    client_secret: str
    r"""The Client Secret of your Google Analytics developer application."""
    refresh_token: str
    r"""The token for obtaining a new access token."""
    access_token: NotRequired[str]
    r"""Access Token for making authenticated requests."""
    auth_type: SourceGoogleAnalyticsDataAPICredentialsAuthType


class CredentialsAuthenticateViaGoogleOauth(BaseModel):
    client_id: str
    r"""The Client ID of your Google Analytics developer application."""

    client_secret: str
    r"""The Client Secret of your Google Analytics developer application."""

    refresh_token: str
    r"""The token for obtaining a new access token."""

    access_token: Optional[str] = None
    r"""Access Token for making authenticated requests."""

    AUTH_TYPE: Annotated[
        Annotated[
            Optional[SourceGoogleAnalyticsDataAPICredentialsAuthType],
            AfterValidator(
                validate_const(SourceGoogleAnalyticsDataAPICredentialsAuthType.CLIENT)
            ),
        ],
        pydantic.Field(alias="auth_type"),
    ] = SourceGoogleAnalyticsDataAPICredentialsAuthType.CLIENT

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["access_token", "auth_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


SourceGoogleAnalyticsDataAPICredentialsTypedDict = TypeAliasType(
    "SourceGoogleAnalyticsDataAPICredentialsTypedDict",
    Union[
        CredentialsServiceAccountKeyAuthenticationTypedDict,
        CredentialsAuthenticateViaGoogleOauthTypedDict,
    ],
)
r"""Credentials for the service"""


SourceGoogleAnalyticsDataAPICredentials = TypeAliasType(
    "SourceGoogleAnalyticsDataAPICredentials",
    Union[
        CredentialsServiceAccountKeyAuthentication,
        CredentialsAuthenticateViaGoogleOauth,
    ],
)
r"""Credentials for the service"""


class CohortReportSettingsTypedDict(TypedDict):
    r"""Optional settings for a cohort report."""

    accumulate: NotRequired[bool]
    r"""If true, accumulates the result from first touch day to the end day"""


class CohortReportSettings(BaseModel):
    r"""Optional settings for a cohort report."""

    accumulate: Optional[bool] = None
    r"""If true, accumulates the result from first touch day to the end day"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["accumulate"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DateRangeTypedDict(TypedDict):
    end_date: date
    start_date: date


class DateRange(BaseModel):
    end_date: Annotated[date, pydantic.Field(alias="endDate")]

    start_date: Annotated[date, pydantic.Field(alias="startDate")]


class Dimension(str, Enum):
    r"""Dimension used by the cohort. Required and only supports `firstSessionDate`"""

    FIRST_SESSION_DATE = "firstSessionDate"


class CohortsTypedDict(TypedDict):
    date_range: DateRangeTypedDict
    dimension: Dimension
    r"""Dimension used by the cohort. Required and only supports `firstSessionDate`"""
    name: NotRequired[str]
    r"""Assigns a name to this cohort. If not set, cohorts are named by their zero based index cohort_0, cohort_1, etc."""


class Cohorts(BaseModel):
    date_range: Annotated[DateRange, pydantic.Field(alias="dateRange")]

    dimension: Dimension
    r"""Dimension used by the cohort. Required and only supports `firstSessionDate`"""

    name: Optional[str] = None
    r"""Assigns a name to this cohort. If not set, cohorts are named by their zero based index cohort_0, cohort_1, etc."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CohortReportsGranularity(str, Enum):
    r"""The granularity used to interpret the startOffset and endOffset for the extended reporting date range for a cohort report."""

    GRANULARITY_UNSPECIFIED = "GRANULARITY_UNSPECIFIED"
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"


class CohortsRangeTypedDict(TypedDict):
    end_offset: int
    r"""Specifies the end date of the extended reporting date range for a cohort report."""
    granularity: CohortReportsGranularity
    r"""The granularity used to interpret the startOffset and endOffset for the extended reporting date range for a cohort report."""
    start_offset: NotRequired[int]
    r"""Specifies the start date of the extended reporting date range for a cohort report."""


class CohortsRange(BaseModel):
    end_offset: Annotated[int, pydantic.Field(alias="endOffset")]
    r"""Specifies the end date of the extended reporting date range for a cohort report."""

    granularity: CohortReportsGranularity
    r"""The granularity used to interpret the startOffset and endOffset for the extended reporting date range for a cohort report."""

    start_offset: Annotated[Optional[int], pydantic.Field(alias="startOffset")] = None
    r"""Specifies the start date of the extended reporting date range for a cohort report."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["startOffset"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceGoogleAnalyticsDataAPICohortReportsCustomReportsArrayEnabled(str, Enum):
    TRUE = "true"


class SourceGoogleAnalyticsDataAPICohortReportsEnabledTypedDict(TypedDict):
    cohort_report_settings: NotRequired[CohortReportSettingsTypedDict]
    r"""Optional settings for a cohort report."""
    cohorts: NotRequired[List[CohortsTypedDict]]
    cohorts_range: NotRequired[CohortsRangeTypedDict]
    enabled: SourceGoogleAnalyticsDataAPICohortReportsCustomReportsArrayEnabled


class SourceGoogleAnalyticsDataAPICohortReportsEnabled(BaseModel):
    cohort_report_settings: Annotated[
        Optional[CohortReportSettings], pydantic.Field(alias="cohortReportSettings")
    ] = None
    r"""Optional settings for a cohort report."""

    cohorts: Optional[List[Cohorts]] = None

    cohorts_range: Annotated[
        Optional[CohortsRange], pydantic.Field(alias="cohortsRange")
    ] = None

    ENABLED: Annotated[
        Annotated[
            Optional[
                SourceGoogleAnalyticsDataAPICohortReportsCustomReportsArrayEnabled
            ],
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPICohortReportsCustomReportsArrayEnabled.TRUE
                )
            ),
        ],
        pydantic.Field(alias="enabled"),
    ] = SourceGoogleAnalyticsDataAPICohortReportsCustomReportsArrayEnabled.TRUE

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["cohortReportSettings", "cohorts", "cohortsRange", "enabled"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CohortReportsEnabled(str, Enum):
    FALSE = "false"


class CohortReportsDisabledTypedDict(TypedDict):
    enabled: CohortReportsEnabled


class CohortReportsDisabled(BaseModel):
    ENABLED: Annotated[
        Annotated[
            Optional[CohortReportsEnabled],
            AfterValidator(validate_const(CohortReportsEnabled.FALSE)),
        ],
        pydantic.Field(alias="enabled"),
    ] = CohortReportsEnabled.FALSE

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["enabled"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


CohortReportsTypedDict = TypeAliasType(
    "CohortReportsTypedDict",
    Union[
        CohortReportsDisabledTypedDict,
        SourceGoogleAnalyticsDataAPICohortReportsEnabledTypedDict,
    ],
)
r"""Cohort reports creates a time series of user retention for the cohort."""


CohortReports = TypeAliasType(
    "CohortReports",
    Union[CohortReportsDisabled, SourceGoogleAnalyticsDataAPICohortReportsEnabled],
)
r"""Cohort reports creates a time series of user retention for the cohort."""


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayFilterName(str, Enum):
    BETWEEN_FILTER = "betweenFilter"


class SourceGoogleAnalyticsDataAPIFromValueValueType(str, Enum):
    DOUBLE_VALUE = "doubleValue"


class FromValueDoubleValueTypedDict(TypedDict):
    value: float
    value_type: SourceGoogleAnalyticsDataAPIFromValueValueType


class FromValueDoubleValue(BaseModel):
    value: float

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFromValueValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFromValueValueType.DOUBLE_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIFromValueValueType.DOUBLE_VALUE


class FromValueValueType(str, Enum):
    INT64_VALUE = "int64Value"


class FromValueInt64ValueTypedDict(TypedDict):
    value: str
    value_type: FromValueValueType


class FromValueInt64Value(BaseModel):
    value: str

    VALUE_TYPE: Annotated[
        Annotated[
            FromValueValueType,
            AfterValidator(validate_const(FromValueValueType.INT64_VALUE)),
        ],
        pydantic.Field(alias="value_type"),
    ] = FromValueValueType.INT64_VALUE


FromValueTypedDict = TypeAliasType(
    "FromValueTypedDict",
    Union[FromValueInt64ValueTypedDict, FromValueDoubleValueTypedDict],
)


FromValue = Annotated[
    Union[
        Annotated[FromValueInt64Value, Tag("int64Value")],
        Annotated[FromValueDoubleValue, Tag("doubleValue")],
    ],
    Discriminator(lambda m: get_discriminator(m, "value_type", "value_type")),
]


class SourceGoogleAnalyticsDataAPIToValueValueType(str, Enum):
    DOUBLE_VALUE = "doubleValue"


class ToValueDoubleValueTypedDict(TypedDict):
    value: float
    value_type: SourceGoogleAnalyticsDataAPIToValueValueType


class ToValueDoubleValue(BaseModel):
    value: float

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIToValueValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIToValueValueType.DOUBLE_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIToValueValueType.DOUBLE_VALUE


class ToValueValueType(str, Enum):
    INT64_VALUE = "int64Value"


class ToValueInt64ValueTypedDict(TypedDict):
    value: str
    value_type: ToValueValueType


class ToValueInt64Value(BaseModel):
    value: str

    VALUE_TYPE: Annotated[
        Annotated[
            ToValueValueType,
            AfterValidator(validate_const(ToValueValueType.INT64_VALUE)),
        ],
        pydantic.Field(alias="value_type"),
    ] = ToValueValueType.INT64_VALUE


ToValueTypedDict = TypeAliasType(
    "ToValueTypedDict", Union[ToValueInt64ValueTypedDict, ToValueDoubleValueTypedDict]
)


ToValue = Annotated[
    Union[
        Annotated[ToValueInt64Value, Tag("int64Value")],
        Annotated[ToValueDoubleValue, Tag("doubleValue")],
    ],
    Discriminator(lambda m: get_discriminator(m, "value_type", "value_type")),
]


class BetweenFilterTypedDict(TypedDict):
    from_value: FromValueTypedDict
    to_value: ToValueTypedDict
    filter_name: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayFilterName


class BetweenFilter(BaseModel):
    from_value: Annotated[FromValue, pydantic.Field(alias="fromValue")]

    to_value: Annotated[ToValue, pydantic.Field(alias="toValue")]

    FILTER_NAME: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayFilterName,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayFilterName.BETWEEN_FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_name"),
    ] = SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayFilterName.BETWEEN_FILTER


class SourceGoogleAnalyticsDataAPIFilterFilterName(str, Enum):
    NUMERIC_FILTER = "numericFilter"


class SourceGoogleAnalyticsDataAPIFilterValidEnums(str, Enum):
    OPERATION_UNSPECIFIED = "OPERATION_UNSPECIFIED"
    EQUAL = "EQUAL"
    LESS_THAN = "LESS_THAN"
    LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL"
    GREATER_THAN = "GREATER_THAN"
    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL"


class ValueValueType(str, Enum):
    DOUBLE_VALUE = "doubleValue"


class DoubleValueTypedDict(TypedDict):
    value: float
    value_type: ValueValueType


class DoubleValue(BaseModel):
    value: float

    VALUE_TYPE: Annotated[
        Annotated[
            ValueValueType, AfterValidator(validate_const(ValueValueType.DOUBLE_VALUE))
        ],
        pydantic.Field(alias="value_type"),
    ] = ValueValueType.DOUBLE_VALUE


class ValueType(str, Enum):
    INT64_VALUE = "int64Value"


class Int64ValueTypedDict(TypedDict):
    value: str
    value_type: ValueType


class Int64Value(BaseModel):
    value: str

    VALUE_TYPE: Annotated[
        Annotated[ValueType, AfterValidator(validate_const(ValueType.INT64_VALUE))],
        pydantic.Field(alias="value_type"),
    ] = ValueType.INT64_VALUE


ValueTypedDict = TypeAliasType(
    "ValueTypedDict", Union[Int64ValueTypedDict, DoubleValueTypedDict]
)


Value = Annotated[
    Union[
        Annotated[Int64Value, Tag("int64Value")],
        Annotated[DoubleValue, Tag("doubleValue")],
    ],
    Discriminator(lambda m: get_discriminator(m, "value_type", "value_type")),
]


class NumericFilterTypedDict(TypedDict):
    operation: List[SourceGoogleAnalyticsDataAPIFilterValidEnums]
    value: ValueTypedDict
    filter_name: SourceGoogleAnalyticsDataAPIFilterFilterName


class NumericFilter(BaseModel):
    operation: List[SourceGoogleAnalyticsDataAPIFilterValidEnums]

    value: Value

    FILTER_NAME: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterFilterName,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFilterFilterName.NUMERIC_FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_name"),
    ] = SourceGoogleAnalyticsDataAPIFilterFilterName.NUMERIC_FILTER


class FilterFilterName(str, Enum):
    IN_LIST_FILTER = "inListFilter"


class InListFilterTypedDict(TypedDict):
    values: List[str]
    case_sensitive: NotRequired[bool]
    filter_name: FilterFilterName


class InListFilter(BaseModel):
    values: List[str]

    case_sensitive: Annotated[Optional[bool], pydantic.Field(alias="caseSensitive")] = (
        None
    )

    FILTER_NAME: Annotated[
        Annotated[
            FilterFilterName,
            AfterValidator(validate_const(FilterFilterName.IN_LIST_FILTER)),
        ],
        pydantic.Field(alias="filter_name"),
    ] = FilterFilterName.IN_LIST_FILTER

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["caseSensitive"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class FilterName(str, Enum):
    STRING_FILTER = "stringFilter"


class FilterValidEnums(str, Enum):
    MATCH_TYPE_UNSPECIFIED = "MATCH_TYPE_UNSPECIFIED"
    EXACT = "EXACT"
    BEGINS_WITH = "BEGINS_WITH"
    ENDS_WITH = "ENDS_WITH"
    CONTAINS = "CONTAINS"
    FULL_REGEXP = "FULL_REGEXP"
    PARTIAL_REGEXP = "PARTIAL_REGEXP"


class StringFilterTypedDict(TypedDict):
    value: str
    case_sensitive: NotRequired[bool]
    filter_name: FilterName
    match_type: NotRequired[List[FilterValidEnums]]


class StringFilter(BaseModel):
    value: str

    case_sensitive: Annotated[Optional[bool], pydantic.Field(alias="caseSensitive")] = (
        None
    )

    FILTER_NAME: Annotated[
        Annotated[FilterName, AfterValidator(validate_const(FilterName.STRING_FILTER))],
        pydantic.Field(alias="filter_name"),
    ] = FilterName.STRING_FILTER

    match_type: Annotated[
        Optional[List[FilterValidEnums]], pydantic.Field(alias="matchType")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["caseSensitive", "matchType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


SourceGoogleAnalyticsDataAPIDimensionsFilterFilterTypedDict = TypeAliasType(
    "SourceGoogleAnalyticsDataAPIDimensionsFilterFilterTypedDict",
    Union[
        InListFilterTypedDict,
        NumericFilterTypedDict,
        BetweenFilterTypedDict,
        StringFilterTypedDict,
    ],
)


SourceGoogleAnalyticsDataAPIDimensionsFilterFilter = Annotated[
    Union[
        Annotated[StringFilter, Tag("stringFilter")],
        Annotated[InListFilter, Tag("inListFilter")],
        Annotated[NumericFilter, Tag("numericFilter")],
        Annotated[BetweenFilter, Tag("betweenFilter")],
    ],
    Discriminator(lambda m: get_discriminator(m, "filter_name", "filter_name")),
]


class SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayFilterType(
    str, Enum
):
    FILTER = "filter"


class DimensionsFilterFilterTypedDict(TypedDict):
    r"""A primitive filter. In the same FilterExpression, all of the filter's field names need to be either all dimensions."""

    field_name: str
    filter_: SourceGoogleAnalyticsDataAPIDimensionsFilterFilterTypedDict
    filter_type: (
        SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayFilterType
    )


class DimensionsFilterFilter(BaseModel):
    r"""A primitive filter. In the same FilterExpression, all of the filter's field names need to be either all dimensions."""

    field_name: str

    filter_: Annotated[
        SourceGoogleAnalyticsDataAPIDimensionsFilterFilter,
        pydantic.Field(alias="filter"),
    ]

    FILTER_TYPE: Annotated[
        Annotated[
            Optional[
                SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayFilterType
            ],
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayFilterType.FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_type"),
    ] = SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayFilterType.FILTER

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["filter_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ExpressionFilter4FilterName(
    str, Enum
):
    BETWEEN_FILTER = "betweenFilter"


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter3ValueType(
    str, Enum
):
    DOUBLE_VALUE = "doubleValue"


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDoubleValueTypedDict(
    TypedDict
):
    value: float
    value_type: SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter3ValueType


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDoubleValue(BaseModel):
    value: float

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter3ValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter3ValueType.DOUBLE_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter3ValueType.DOUBLE_VALUE


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilterValueType(
    str, Enum
):
    INT64_VALUE = "int64Value"


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayInt64ValueTypedDict(
    TypedDict
):
    value: str
    value_type: SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilterValueType


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayInt64Value(BaseModel):
    value: str

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilterValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilterValueType.INT64_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilterValueType.INT64_VALUE


SourceGoogleAnalyticsDataAPIFilterFromValueTypedDict = TypeAliasType(
    "SourceGoogleAnalyticsDataAPIFilterFromValueTypedDict",
    Union[
        SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayInt64ValueTypedDict,
        SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDoubleValueTypedDict,
    ],
)


SourceGoogleAnalyticsDataAPIFilterFromValue = Annotated[
    Union[
        Annotated[
            SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayInt64Value,
            Tag("int64Value"),
        ],
        Annotated[
            SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDoubleValue,
            Tag("doubleValue"),
        ],
    ],
    Discriminator(lambda m: get_discriminator(m, "value_type", "value_type")),
]


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter3ValueType(
    str, Enum
):
    DOUBLE_VALUE = "doubleValue"


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDoubleValueTypedDict(
    TypedDict
):
    value: float
    value_type: SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter3ValueType


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDoubleValue(BaseModel):
    value: float

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter3ValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter3ValueType.DOUBLE_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter3ValueType.DOUBLE_VALUE


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilterValueType(
    str, Enum
):
    INT64_VALUE = "int64Value"


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayInt64ValueTypedDict(
    TypedDict
):
    value: str
    value_type: SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilterValueType


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayInt64Value(BaseModel):
    value: str

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilterValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilterValueType.INT64_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilterValueType.INT64_VALUE


SourceGoogleAnalyticsDataAPIFilterToValueTypedDict = TypeAliasType(
    "SourceGoogleAnalyticsDataAPIFilterToValueTypedDict",
    Union[
        SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayInt64ValueTypedDict,
        SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDoubleValueTypedDict,
    ],
)


SourceGoogleAnalyticsDataAPIFilterToValue = Annotated[
    Union[
        Annotated[
            SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayInt64Value,
            Tag("int64Value"),
        ],
        Annotated[
            SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDoubleValue,
            Tag("doubleValue"),
        ],
    ],
    Discriminator(lambda m: get_discriminator(m, "value_type", "value_type")),
]


class SourceGoogleAnalyticsDataAPIFilterBetweenFilterTypedDict(TypedDict):
    from_value: SourceGoogleAnalyticsDataAPIFilterFromValueTypedDict
    to_value: SourceGoogleAnalyticsDataAPIFilterToValueTypedDict
    filter_name: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ExpressionFilter4FilterName


class SourceGoogleAnalyticsDataAPIFilterBetweenFilter(BaseModel):
    from_value: Annotated[
        SourceGoogleAnalyticsDataAPIFilterFromValue, pydantic.Field(alias="fromValue")
    ]

    to_value: Annotated[
        SourceGoogleAnalyticsDataAPIFilterToValue, pydantic.Field(alias="toValue")
    ]

    FILTER_NAME: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ExpressionFilter4FilterName,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ExpressionFilter4FilterName.BETWEEN_FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_name"),
    ] = SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ExpressionFilter4FilterName.BETWEEN_FILTER


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ExpressionFilterFilterName(
    str, Enum
):
    NUMERIC_FILTER = "numericFilter"


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ValidEnums(
    str, Enum
):
    OPERATION_UNSPECIFIED = "OPERATION_UNSPECIFIED"
    EQUAL = "EQUAL"
    LESS_THAN = "LESS_THAN"
    LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL"
    GREATER_THAN = "GREATER_THAN"
    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL"


class SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilterValueType(
    str, Enum
):
    DOUBLE_VALUE = "doubleValue"


class SourceGoogleAnalyticsDataAPIValueDoubleValueTypedDict(TypedDict):
    value: float
    value_type: SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilterValueType


class SourceGoogleAnalyticsDataAPIValueDoubleValue(BaseModel):
    value: float

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilterValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilterValueType.DOUBLE_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilterValueType.DOUBLE_VALUE


class SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterValueType(
    str, Enum
):
    INT64_VALUE = "int64Value"


class SourceGoogleAnalyticsDataAPIValueInt64ValueTypedDict(TypedDict):
    value: str
    value_type: (
        SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterValueType
    )


class SourceGoogleAnalyticsDataAPIValueInt64Value(BaseModel):
    value: str

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterValueType.INT64_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterValueType.INT64_VALUE


SourceGoogleAnalyticsDataAPIFilterValueTypedDict = TypeAliasType(
    "SourceGoogleAnalyticsDataAPIFilterValueTypedDict",
    Union[
        SourceGoogleAnalyticsDataAPIValueInt64ValueTypedDict,
        SourceGoogleAnalyticsDataAPIValueDoubleValueTypedDict,
    ],
)


SourceGoogleAnalyticsDataAPIFilterValue = Annotated[
    Union[
        Annotated[SourceGoogleAnalyticsDataAPIValueInt64Value, Tag("int64Value")],
        Annotated[SourceGoogleAnalyticsDataAPIValueDoubleValue, Tag("doubleValue")],
    ],
    Discriminator(lambda m: get_discriminator(m, "value_type", "value_type")),
]


class SourceGoogleAnalyticsDataAPIFilterNumericFilterTypedDict(TypedDict):
    operation: List[
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ValidEnums
    ]
    value: SourceGoogleAnalyticsDataAPIFilterValueTypedDict
    filter_name: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ExpressionFilterFilterName


class SourceGoogleAnalyticsDataAPIFilterNumericFilter(BaseModel):
    operation: List[
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ValidEnums
    ]

    value: SourceGoogleAnalyticsDataAPIFilterValue

    FILTER_NAME: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ExpressionFilterFilterName,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ExpressionFilterFilterName.NUMERIC_FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_name"),
    ] = SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ExpressionFilterFilterName.NUMERIC_FILTER


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ExpressionFilterName(
    str, Enum
):
    IN_LIST_FILTER = "inListFilter"


class SourceGoogleAnalyticsDataAPIFilterInListFilterTypedDict(TypedDict):
    values: List[str]
    case_sensitive: NotRequired[bool]
    filter_name: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ExpressionFilterName


class SourceGoogleAnalyticsDataAPIFilterInListFilter(BaseModel):
    values: List[str]

    case_sensitive: Annotated[Optional[bool], pydantic.Field(alias="caseSensitive")] = (
        None
    )

    FILTER_NAME: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ExpressionFilterName,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ExpressionFilterName.IN_LIST_FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_name"),
    ] = SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3ExpressionFilterName.IN_LIST_FILTER

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["caseSensitive"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3FilterName(
    str, Enum
):
    STRING_FILTER = "stringFilter"


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilterValidEnums(
    str, Enum
):
    MATCH_TYPE_UNSPECIFIED = "MATCH_TYPE_UNSPECIFIED"
    EXACT = "EXACT"
    BEGINS_WITH = "BEGINS_WITH"
    ENDS_WITH = "ENDS_WITH"
    CONTAINS = "CONTAINS"
    FULL_REGEXP = "FULL_REGEXP"
    PARTIAL_REGEXP = "PARTIAL_REGEXP"


class SourceGoogleAnalyticsDataAPIFilterStringFilterTypedDict(TypedDict):
    value: str
    case_sensitive: NotRequired[bool]
    filter_name: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3FilterName
    match_type: NotRequired[
        List[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilterValidEnums
        ]
    ]


class SourceGoogleAnalyticsDataAPIFilterStringFilter(BaseModel):
    value: str

    case_sensitive: Annotated[Optional[bool], pydantic.Field(alias="caseSensitive")] = (
        None
    )

    FILTER_NAME: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3FilterName,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3FilterName.STRING_FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_name"),
    ] = SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter3FilterName.STRING_FILTER

    match_type: Annotated[
        Optional[
            List[
                SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilterValidEnums
            ]
        ],
        pydantic.Field(alias="matchType"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["caseSensitive", "matchType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayFilterTypedDict = (
    TypeAliasType(
        "SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayFilterTypedDict",
        Union[
            SourceGoogleAnalyticsDataAPIFilterInListFilterTypedDict,
            SourceGoogleAnalyticsDataAPIFilterNumericFilterTypedDict,
            SourceGoogleAnalyticsDataAPIFilterBetweenFilterTypedDict,
            SourceGoogleAnalyticsDataAPIFilterStringFilterTypedDict,
        ],
    )
)


SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayFilter = Annotated[
    Union[
        Annotated[SourceGoogleAnalyticsDataAPIFilterStringFilter, Tag("stringFilter")],
        Annotated[SourceGoogleAnalyticsDataAPIFilterInListFilter, Tag("inListFilter")],
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterNumericFilter, Tag("numericFilter")
        ],
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterBetweenFilter, Tag("betweenFilter")
        ],
    ],
    Discriminator(lambda m: get_discriminator(m, "filter_name", "filter_name")),
]


class SourceGoogleAnalyticsDataAPIDimensionsFilterExpressionTypedDict(TypedDict):
    field_name: str
    filter_: (
        SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayFilterTypedDict
    )


class SourceGoogleAnalyticsDataAPIDimensionsFilterExpression(BaseModel):
    field_name: str

    filter_: Annotated[
        SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayFilter,
        pydantic.Field(alias="filter"),
    ]


class SourceGoogleAnalyticsDataAPIDimensionsFilterFilterType(str, Enum):
    NOT_EXPRESSION = "notExpression"


class NotExpressionTypedDict(TypedDict):
    r"""The FilterExpression is NOT of notExpression."""

    expression: NotRequired[
        SourceGoogleAnalyticsDataAPIDimensionsFilterExpressionTypedDict
    ]
    filter_type: SourceGoogleAnalyticsDataAPIDimensionsFilterFilterType


class NotExpression(BaseModel):
    r"""The FilterExpression is NOT of notExpression."""

    expression: Optional[SourceGoogleAnalyticsDataAPIDimensionsFilterExpression] = None

    FILTER_TYPE: Annotated[
        Annotated[
            Optional[SourceGoogleAnalyticsDataAPIDimensionsFilterFilterType],
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIDimensionsFilterFilterType.NOT_EXPRESSION
                )
            ),
        ],
        pydantic.Field(alias="filter_type"),
    ] = SourceGoogleAnalyticsDataAPIDimensionsFilterFilterType.NOT_EXPRESSION

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["expression", "filter_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter2ExpressionsFilterName(
    str, Enum
):
    BETWEEN_FILTER = "betweenFilter"


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterValueType(
    str, Enum
):
    DOUBLE_VALUE = "doubleValue"


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilterDoubleValueTypedDict(
    TypedDict
):
    value: float
    value_type: (
        SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterValueType
    )


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilterDoubleValue(
    BaseModel
):
    value: float

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterValueType.DOUBLE_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterValueType.DOUBLE_VALUE


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter2ValueType(
    str, Enum
):
    INT64_VALUE = "int64Value"


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilterInt64ValueTypedDict(
    TypedDict
):
    value: str
    value_type: SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter2ValueType


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilterInt64Value(
    BaseModel
):
    value: str

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter2ValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter2ValueType.INT64_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter2ValueType.INT64_VALUE


SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterFromValueTypedDict = TypeAliasType(
    "SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterFromValueTypedDict",
    Union[
        SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilterInt64ValueTypedDict,
        SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilterDoubleValueTypedDict,
    ],
)


SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterFromValue = Annotated[
    Union[
        Annotated[
            SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilterInt64Value,
            Tag("int64Value"),
        ],
        Annotated[
            SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilterDoubleValue,
            Tag("doubleValue"),
        ],
    ],
    Discriminator(lambda m: get_discriminator(m, "value_type", "value_type")),
]


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterValueType(
    str, Enum
):
    DOUBLE_VALUE = "doubleValue"


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilterDoubleValueTypedDict(
    TypedDict
):
    value: float
    value_type: (
        SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterValueType
    )


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilterDoubleValue(
    BaseModel
):
    value: float

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterValueType.DOUBLE_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterValueType.DOUBLE_VALUE


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter2ValueType(
    str, Enum
):
    INT64_VALUE = "int64Value"


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilterInt64ValueTypedDict(
    TypedDict
):
    value: str
    value_type: SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter2ValueType


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilterInt64Value(
    BaseModel
):
    value: str

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter2ValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter2ValueType.INT64_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter2ValueType.INT64_VALUE


SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterToValueTypedDict = TypeAliasType(
    "SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterToValueTypedDict",
    Union[
        SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilterInt64ValueTypedDict,
        SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilterDoubleValueTypedDict,
    ],
)


SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterToValue = Annotated[
    Union[
        Annotated[
            SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilterInt64Value,
            Tag("int64Value"),
        ],
        Annotated[
            SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilterDoubleValue,
            Tag("doubleValue"),
        ],
    ],
    Discriminator(lambda m: get_discriminator(m, "value_type", "value_type")),
]


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterBetweenFilterTypedDict(
    TypedDict
):
    from_value: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterFromValueTypedDict
    to_value: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterToValueTypedDict
    filter_name: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter2ExpressionsFilterName


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterBetweenFilter(
    BaseModel
):
    from_value: Annotated[
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterFromValue,
        pydantic.Field(alias="fromValue"),
    ]

    to_value: Annotated[
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterToValue,
        pydantic.Field(alias="toValue"),
    ]

    FILTER_NAME: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter2ExpressionsFilterName,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter2ExpressionsFilterName.BETWEEN_FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_name"),
    ] = SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter2ExpressionsFilterName.BETWEEN_FILTER


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter2FilterName(
    str, Enum
):
    NUMERIC_FILTER = "numericFilter"


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterValidEnums(
    str, Enum
):
    OPERATION_UNSPECIFIED = "OPERATION_UNSPECIFIED"
    EQUAL = "EQUAL"
    LESS_THAN = "LESS_THAN"
    LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL"
    GREATER_THAN = "GREATER_THAN"
    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL"


class SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter2ExpressionsValueType(
    str, Enum
):
    DOUBLE_VALUE = "doubleValue"


class SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDoubleValueTypedDict(
    TypedDict
):
    value: float
    value_type: SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter2ExpressionsValueType


class SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDoubleValue(
    BaseModel
):
    value: float

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter2ExpressionsValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter2ExpressionsValueType.DOUBLE_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter2ExpressionsValueType.DOUBLE_VALUE


class SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter2ValueType(
    str, Enum
):
    INT64_VALUE = "int64Value"


class SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterInt64ValueTypedDict(
    TypedDict
):
    value: str
    value_type: SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter2ValueType


class SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterInt64Value(
    BaseModel
):
    value: str

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter2ValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter2ValueType.INT64_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter2ValueType.INT64_VALUE


SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterValueTypedDict = TypeAliasType(
    "SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterValueTypedDict",
    Union[
        SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterInt64ValueTypedDict,
        SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDoubleValueTypedDict,
    ],
)


SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterValue = Annotated[
    Union[
        Annotated[
            SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterInt64Value,
            Tag("int64Value"),
        ],
        Annotated[
            SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDoubleValue,
            Tag("doubleValue"),
        ],
    ],
    Discriminator(lambda m: get_discriminator(m, "value_type", "value_type")),
]


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterNumericFilterTypedDict(
    TypedDict
):
    operation: List[
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterValidEnums
    ]
    value: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterValueTypedDict
    filter_name: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter2FilterName


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterNumericFilter(
    BaseModel
):
    operation: List[
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterValidEnums
    ]

    value: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterValue

    FILTER_NAME: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter2FilterName,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter2FilterName.NUMERIC_FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_name"),
    ] = SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter2FilterName.NUMERIC_FILTER


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilterFilterName(
    str, Enum
):
    IN_LIST_FILTER = "inListFilter"


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterInListFilterTypedDict(
    TypedDict
):
    values: List[str]
    case_sensitive: NotRequired[bool]
    filter_name: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilterFilterName


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterInListFilter(
    BaseModel
):
    values: List[str]

    case_sensitive: Annotated[Optional[bool], pydantic.Field(alias="caseSensitive")] = (
        None
    )

    FILTER_NAME: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilterFilterName,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilterFilterName.IN_LIST_FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_name"),
    ] = SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilterFilterName.IN_LIST_FILTER

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["caseSensitive"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterFilterName(
    str, Enum
):
    STRING_FILTER = "stringFilter"


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter2ValidEnums(
    str, Enum
):
    MATCH_TYPE_UNSPECIFIED = "MATCH_TYPE_UNSPECIFIED"
    EXACT = "EXACT"
    BEGINS_WITH = "BEGINS_WITH"
    ENDS_WITH = "ENDS_WITH"
    CONTAINS = "CONTAINS"
    FULL_REGEXP = "FULL_REGEXP"
    PARTIAL_REGEXP = "PARTIAL_REGEXP"


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterStringFilterTypedDict(
    TypedDict
):
    value: str
    case_sensitive: NotRequired[bool]
    filter_name: (
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterFilterName
    )
    match_type: NotRequired[
        List[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter2ValidEnums
        ]
    ]


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterStringFilter(
    BaseModel
):
    value: str

    case_sensitive: Annotated[Optional[bool], pydantic.Field(alias="caseSensitive")] = (
        None
    )

    FILTER_NAME: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterFilterName,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterFilterName.STRING_FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_name"),
    ] = SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterFilterName.STRING_FILTER

    match_type: Annotated[
        Optional[
            List[
                SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter2ValidEnums
            ]
        ],
        pydantic.Field(alias="matchType"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["caseSensitive", "matchType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayDimensionFilter2FilterTypedDict = TypeAliasType(
    "SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayDimensionFilter2FilterTypedDict",
    Union[
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterInListFilterTypedDict,
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterNumericFilterTypedDict,
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterBetweenFilterTypedDict,
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterStringFilterTypedDict,
    ],
)


SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayDimensionFilter2Filter = Annotated[
    Union[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterStringFilter,
            Tag("stringFilter"),
        ],
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterInListFilter,
            Tag("inListFilter"),
        ],
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterNumericFilter,
            Tag("numericFilter"),
        ],
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterBetweenFilter,
            Tag("betweenFilter"),
        ],
    ],
    Discriminator(lambda m: get_discriminator(m, "filter_name", "filter_name")),
]


class DimensionsFilterExpressionTypedDict(TypedDict):
    field_name: str
    filter_: SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayDimensionFilter2FilterTypedDict


class DimensionsFilterExpression(BaseModel):
    field_name: str

    filter_: Annotated[
        SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayDimensionFilter2Filter,
        pydantic.Field(alias="filter"),
    ]


class DimensionsFilterFilterType(str, Enum):
    OR_GROUP = "orGroup"


class OrGroupTypedDict(TypedDict):
    r"""The FilterExpressions in orGroup have an OR relationship."""

    expressions: List[DimensionsFilterExpressionTypedDict]
    filter_type: DimensionsFilterFilterType


class OrGroup(BaseModel):
    r"""The FilterExpressions in orGroup have an OR relationship."""

    expressions: List[DimensionsFilterExpression]

    FILTER_TYPE: Annotated[
        Annotated[
            DimensionsFilterFilterType,
            AfterValidator(validate_const(DimensionsFilterFilterType.OR_GROUP)),
        ],
        pydantic.Field(alias="filter_type"),
    ] = DimensionsFilterFilterType.OR_GROUP


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsFilter4FilterName(
    str, Enum
):
    BETWEEN_FILTER = "betweenFilter"


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValueType(
    str, Enum
):
    DOUBLE_VALUE = "doubleValue"


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDoubleValueTypedDict(
    TypedDict
):
    value: float
    value_type: SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValueType


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDoubleValue(
    BaseModel
):
    value: float

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValueType.DOUBLE_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValueType.DOUBLE_VALUE


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter1ValueType(
    str, Enum
):
    INT64_VALUE = "int64Value"


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterInt64ValueTypedDict(
    TypedDict
):
    value: str
    value_type: SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter1ValueType


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterInt64Value(
    BaseModel
):
    value: str

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter1ValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter1ValueType.INT64_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilter1ValueType.INT64_VALUE


SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayFromValueTypedDict = TypeAliasType(
    "SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayFromValueTypedDict",
    Union[
        SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterInt64ValueTypedDict,
        SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDoubleValueTypedDict,
    ],
)


SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayFromValue = Annotated[
    Union[
        Annotated[
            SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterInt64Value,
            Tag("int64Value"),
        ],
        Annotated[
            SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDoubleValue,
            Tag("doubleValue"),
        ],
    ],
    Discriminator(lambda m: get_discriminator(m, "value_type", "value_type")),
]


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValueType(
    str, Enum
):
    DOUBLE_VALUE = "doubleValue"


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDoubleValueTypedDict(
    TypedDict
):
    value: float
    value_type: SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValueType


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDoubleValue(
    BaseModel
):
    value: float

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValueType.DOUBLE_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValueType.DOUBLE_VALUE


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter1ValueType(
    str, Enum
):
    INT64_VALUE = "int64Value"


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterInt64ValueTypedDict(
    TypedDict
):
    value: str
    value_type: SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter1ValueType


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterInt64Value(
    BaseModel
):
    value: str

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter1ValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter1ValueType.INT64_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilter1ValueType.INT64_VALUE


SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayToValueTypedDict = TypeAliasType(
    "SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayToValueTypedDict",
    Union[
        SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterInt64ValueTypedDict,
        SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDoubleValueTypedDict,
    ],
)


SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayToValue = Annotated[
    Union[
        Annotated[
            SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterInt64Value,
            Tag("int64Value"),
        ],
        Annotated[
            SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDoubleValue,
            Tag("doubleValue"),
        ],
    ],
    Discriminator(lambda m: get_discriminator(m, "value_type", "value_type")),
]


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayBetweenFilterTypedDict(
    TypedDict
):
    from_value: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayFromValueTypedDict
    to_value: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayToValueTypedDict
    filter_name: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsFilter4FilterName


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayBetweenFilter(BaseModel):
    from_value: Annotated[
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayFromValue,
        pydantic.Field(alias="fromValue"),
    ]

    to_value: Annotated[
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayToValue,
        pydantic.Field(alias="toValue"),
    ]

    FILTER_NAME: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsFilter4FilterName,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsFilter4FilterName.BETWEEN_FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_name"),
    ] = SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsFilter4FilterName.BETWEEN_FILTER


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsFilterFilterName(
    str, Enum
):
    NUMERIC_FILTER = "numericFilter"


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValidEnums(
    str, Enum
):
    OPERATION_UNSPECIFIED = "OPERATION_UNSPECIFIED"
    EQUAL = "EQUAL"
    LESS_THAN = "LESS_THAN"
    LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL"
    GREATER_THAN = "GREATER_THAN"
    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL"


class SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValueType(
    str, Enum
):
    DOUBLE_VALUE = "doubleValue"


class SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDoubleValueTypedDict(
    TypedDict
):
    value: float
    value_type: SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValueType


class SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDoubleValue(BaseModel):
    value: float

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValueType.DOUBLE_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValueType.DOUBLE_VALUE


class SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter1ValueType(
    str, Enum
):
    INT64_VALUE = "int64Value"


class SourceGoogleAnalyticsDataAPIValueCustomReportsArrayInt64ValueTypedDict(TypedDict):
    value: str
    value_type: SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter1ValueType


class SourceGoogleAnalyticsDataAPIValueCustomReportsArrayInt64Value(BaseModel):
    value: str

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter1ValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter1ValueType.INT64_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDimensionsFilter1ValueType.INT64_VALUE


SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayValueTypedDict = TypeAliasType(
    "SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayValueTypedDict",
    Union[
        SourceGoogleAnalyticsDataAPIValueCustomReportsArrayInt64ValueTypedDict,
        SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDoubleValueTypedDict,
    ],
)


SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayValue = Annotated[
    Union[
        Annotated[
            SourceGoogleAnalyticsDataAPIValueCustomReportsArrayInt64Value,
            Tag("int64Value"),
        ],
        Annotated[
            SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDoubleValue,
            Tag("doubleValue"),
        ],
    ],
    Discriminator(lambda m: get_discriminator(m, "value_type", "value_type")),
]


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayNumericFilterTypedDict(
    TypedDict
):
    operation: List[
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValidEnums
    ]
    value: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayValueTypedDict
    filter_name: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsFilterFilterName


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayNumericFilter(BaseModel):
    operation: List[
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsValidEnums
    ]

    value: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayValue

    FILTER_NAME: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsFilterFilterName,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsFilterFilterName.NUMERIC_FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_name"),
    ] = SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsFilterFilterName.NUMERIC_FILTER


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsFilterName(
    str, Enum
):
    IN_LIST_FILTER = "inListFilter"


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayInListFilterTypedDict(
    TypedDict
):
    values: List[str]
    case_sensitive: NotRequired[bool]
    filter_name: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsFilterName


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayInListFilter(BaseModel):
    values: List[str]

    case_sensitive: Annotated[Optional[bool], pydantic.Field(alias="caseSensitive")] = (
        None
    )

    FILTER_NAME: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsFilterName,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsFilterName.IN_LIST_FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_name"),
    ] = SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ExpressionsFilterName.IN_LIST_FILTER

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["caseSensitive"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1FilterName(
    str, Enum
):
    STRING_FILTER = "stringFilter"


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ValidEnums(
    str, Enum
):
    MATCH_TYPE_UNSPECIFIED = "MATCH_TYPE_UNSPECIFIED"
    EXACT = "EXACT"
    BEGINS_WITH = "BEGINS_WITH"
    ENDS_WITH = "ENDS_WITH"
    CONTAINS = "CONTAINS"
    FULL_REGEXP = "FULL_REGEXP"
    PARTIAL_REGEXP = "PARTIAL_REGEXP"


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayStringFilterTypedDict(
    TypedDict
):
    value: str
    case_sensitive: NotRequired[bool]
    filter_name: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1FilterName
    match_type: NotRequired[
        List[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ValidEnums
        ]
    ]


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayStringFilter(BaseModel):
    value: str

    case_sensitive: Annotated[Optional[bool], pydantic.Field(alias="caseSensitive")] = (
        None
    )

    FILTER_NAME: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1FilterName,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1FilterName.STRING_FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_name"),
    ] = SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1FilterName.STRING_FILTER

    match_type: Annotated[
        Optional[
            List[
                SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterDimensionsFilter1ValidEnums
            ]
        ],
        pydantic.Field(alias="matchType"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["caseSensitive", "matchType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayDimensionFilterFilterTypedDict = TypeAliasType(
    "SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayDimensionFilterFilterTypedDict",
    Union[
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayInListFilterTypedDict,
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayNumericFilterTypedDict,
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayBetweenFilterTypedDict,
        SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayStringFilterTypedDict,
    ],
)


SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayDimensionFilterFilter = (
    Annotated[
        Union[
            Annotated[
                SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayStringFilter,
                Tag("stringFilter"),
            ],
            Annotated[
                SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayInListFilter,
                Tag("inListFilter"),
            ],
            Annotated[
                SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayNumericFilter,
                Tag("numericFilter"),
            ],
            Annotated[
                SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayBetweenFilter,
                Tag("betweenFilter"),
            ],
        ],
        Discriminator(lambda m: get_discriminator(m, "filter_name", "filter_name")),
    ]
)


class ExpressionTypedDict(TypedDict):
    field_name: str
    filter_: SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayDimensionFilterFilterTypedDict


class Expression(BaseModel):
    field_name: str

    filter_: Annotated[
        SourceGoogleAnalyticsDataAPIDimensionsFilterCustomReportsArrayDimensionFilterFilter,
        pydantic.Field(alias="filter"),
    ]


class FilterType(str, Enum):
    AND_GROUP = "andGroup"


class AndGroupTypedDict(TypedDict):
    r"""The FilterExpressions in andGroup have an AND relationship."""

    expressions: List[ExpressionTypedDict]
    filter_type: FilterType


class AndGroup(BaseModel):
    r"""The FilterExpressions in andGroup have an AND relationship."""

    expressions: List[Expression]

    FILTER_TYPE: Annotated[
        Annotated[FilterType, AfterValidator(validate_const(FilterType.AND_GROUP))],
        pydantic.Field(alias="filter_type"),
    ] = FilterType.AND_GROUP


DimensionsFilterTypedDict = TypeAliasType(
    "DimensionsFilterTypedDict",
    Union[
        AndGroupTypedDict,
        OrGroupTypedDict,
        NotExpressionTypedDict,
        DimensionsFilterFilterTypedDict,
    ],
)
r"""Dimensions filter"""


DimensionsFilter = TypeAliasType(
    "DimensionsFilter", Union[AndGroup, OrGroup, NotExpression, DimensionsFilterFilter]
)
r"""Dimensions filter"""


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayMetricFilterMetricsFilter4FilterFilterName(
    str, Enum
):
    BETWEEN_FILTER = "betweenFilter"


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayMetricFilterValueType(
    str, Enum
):
    DOUBLE_VALUE = "doubleValue"


class SourceGoogleAnalyticsDataAPIFromValueDoubleValueTypedDict(TypedDict):
    value: float
    value_type: (
        SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayMetricFilterValueType
    )


class SourceGoogleAnalyticsDataAPIFromValueDoubleValue(BaseModel):
    value: float

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayMetricFilterValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayMetricFilterValueType.DOUBLE_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayMetricFilterValueType.DOUBLE_VALUE


class SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayValueType(str, Enum):
    INT64_VALUE = "int64Value"


class SourceGoogleAnalyticsDataAPIFromValueInt64ValueTypedDict(TypedDict):
    value: str
    value_type: SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayValueType


class SourceGoogleAnalyticsDataAPIFromValueInt64Value(BaseModel):
    value: str

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayValueType.INT64_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayValueType.INT64_VALUE


FilterFromValueTypedDict = TypeAliasType(
    "FilterFromValueTypedDict",
    Union[
        SourceGoogleAnalyticsDataAPIFromValueInt64ValueTypedDict,
        SourceGoogleAnalyticsDataAPIFromValueDoubleValueTypedDict,
    ],
)


FilterFromValue = Annotated[
    Union[
        Annotated[SourceGoogleAnalyticsDataAPIFromValueInt64Value, Tag("int64Value")],
        Annotated[SourceGoogleAnalyticsDataAPIFromValueDoubleValue, Tag("doubleValue")],
    ],
    Discriminator(lambda m: get_discriminator(m, "value_type", "value_type")),
]


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayMetricFilterValueType(
    str, Enum
):
    DOUBLE_VALUE = "doubleValue"


class SourceGoogleAnalyticsDataAPIToValueDoubleValueTypedDict(TypedDict):
    value: float
    value_type: (
        SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayMetricFilterValueType
    )


class SourceGoogleAnalyticsDataAPIToValueDoubleValue(BaseModel):
    value: float

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayMetricFilterValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayMetricFilterValueType.DOUBLE_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayMetricFilterValueType.DOUBLE_VALUE


class SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayValueType(str, Enum):
    INT64_VALUE = "int64Value"


class SourceGoogleAnalyticsDataAPIToValueInt64ValueTypedDict(TypedDict):
    value: str
    value_type: SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayValueType


class SourceGoogleAnalyticsDataAPIToValueInt64Value(BaseModel):
    value: str

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayValueType.INT64_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayValueType.INT64_VALUE


FilterToValueTypedDict = TypeAliasType(
    "FilterToValueTypedDict",
    Union[
        SourceGoogleAnalyticsDataAPIToValueInt64ValueTypedDict,
        SourceGoogleAnalyticsDataAPIToValueDoubleValueTypedDict,
    ],
)


FilterToValue = Annotated[
    Union[
        Annotated[SourceGoogleAnalyticsDataAPIToValueInt64Value, Tag("int64Value")],
        Annotated[SourceGoogleAnalyticsDataAPIToValueDoubleValue, Tag("doubleValue")],
    ],
    Discriminator(lambda m: get_discriminator(m, "value_type", "value_type")),
]


class FilterBetweenFilterTypedDict(TypedDict):
    from_value: FilterFromValueTypedDict
    to_value: FilterToValueTypedDict
    filter_name: SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayMetricFilterMetricsFilter4FilterFilterName


class FilterBetweenFilter(BaseModel):
    from_value: Annotated[FilterFromValue, pydantic.Field(alias="fromValue")]

    to_value: Annotated[FilterToValue, pydantic.Field(alias="toValue")]

    FILTER_NAME: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayMetricFilterMetricsFilter4FilterFilterName,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayMetricFilterMetricsFilter4FilterFilterName.BETWEEN_FILTER
                )
            ),
        ],
        pydantic.Field(alias="filter_name"),
    ] = SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayMetricFilterMetricsFilter4FilterFilterName.BETWEEN_FILTER


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayMetricFilterMetricsFilter4FilterName(
    str, Enum
):
    NUMERIC_FILTER = "numericFilter"


class SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayMetricFilterValidEnums(
    str, Enum
):
    OPERATION_UNSPECIFIED = "OPERATION_UNSPECIFIED"
    EQUAL = "EQUAL"
    LESS_THAN = "LESS_THAN"
    LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL"
    GREATER_THAN = "GREATER_THAN"
    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL"


class SourceGoogleAnalyticsDataAPIValueCustomReportsArrayValueType(str, Enum):
    DOUBLE_VALUE = "doubleValue"


class ValueDoubleValueTypedDict(TypedDict):
    value: float
    value_type: SourceGoogleAnalyticsDataAPIValueCustomReportsArrayValueType


class ValueDoubleValue(BaseModel):
    value: float

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIValueCustomReportsArrayValueType,
            AfterValidator(
                validate_const(
                    SourceGoogleAnalyticsDataAPIValueCustomReportsArrayValueType.DOUBLE_VALUE
                )
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIValueCustomReportsArrayValueType.DOUBLE_VALUE


class SourceGoogleAnalyticsDataAPIValueValueType(str, Enum):
    INT64_VALUE = "int64Value"


class ValueInt64ValueTypedDict(TypedDict):
    value: str
    value_type: SourceGoogleAnalyticsDataAPIValueValueType


class ValueInt64Value(BaseModel):
    value: str

    VALUE_TYPE: Annotated[
        Annotated[
            SourceGoogleAnalyticsDataAPIValueValueType,
            AfterValidator(
                validate_const(SourceGoogleAnalyticsDataAPIValueValueType.INT64_VALUE)
            ),
        ],
        pydantic.Field(alias="value_type"),
    ] = SourceGoogleAnalyticsDataAPIValueValueType.INT64_VALUE


try:
    CredentialsServiceAccountKeyAuthentication.model_rebuild()
except NameError:
    pass
try:
    CredentialsAuthenticateViaGoogleOauth.model_rebuild()
except NameError:
    pass
try:
    DateRange.model_rebuild()
except NameError:
    pass
try:
    Cohorts.model_rebuild()
except NameError:
    pass
try:
    CohortsRange.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPICohortReportsEnabled.model_rebuild()
except NameError:
    pass
try:
    CohortReportsDisabled.model_rebuild()
except NameError:
    pass
try:
    FromValueDoubleValue.model_rebuild()
except NameError:
    pass
try:
    FromValueInt64Value.model_rebuild()
except NameError:
    pass
try:
    ToValueDoubleValue.model_rebuild()
except NameError:
    pass
try:
    ToValueInt64Value.model_rebuild()
except NameError:
    pass
try:
    BetweenFilter.model_rebuild()
except NameError:
    pass
try:
    DoubleValue.model_rebuild()
except NameError:
    pass
try:
    Int64Value.model_rebuild()
except NameError:
    pass
try:
    NumericFilter.model_rebuild()
except NameError:
    pass
try:
    InListFilter.model_rebuild()
except NameError:
    pass
try:
    StringFilter.model_rebuild()
except NameError:
    pass
try:
    DimensionsFilterFilter.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDoubleValue.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayInt64Value.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDoubleValue.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayInt64Value.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFilterBetweenFilter.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIValueDoubleValue.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIValueInt64Value.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFilterNumericFilter.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFilterInListFilter.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFilterStringFilter.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIDimensionsFilterExpression.model_rebuild()
except NameError:
    pass
try:
    NotExpression.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilterDoubleValue.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDimensionsFilterInt64Value.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilterDoubleValue.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDimensionsFilterInt64Value.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterBetweenFilter.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterDoubleValue.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDimensionFilterInt64Value.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterNumericFilter.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterInListFilter.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayDimensionFilterStringFilter.model_rebuild()
except NameError:
    pass
try:
    DimensionsFilterExpression.model_rebuild()
except NameError:
    pass
try:
    OrGroup.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterDoubleValue.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFromValueCustomReportsArrayDimensionFilterInt64Value.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterDoubleValue.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIToValueCustomReportsArrayDimensionFilterInt64Value.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayBetweenFilter.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIValueCustomReportsArrayDoubleValue.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIValueCustomReportsArrayInt64Value.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayNumericFilter.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayInListFilter.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFilterCustomReportsArrayStringFilter.model_rebuild()
except NameError:
    pass
try:
    Expression.model_rebuild()
except NameError:
    pass
try:
    AndGroup.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFromValueDoubleValue.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIFromValueInt64Value.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIToValueDoubleValue.model_rebuild()
except NameError:
    pass
try:
    SourceGoogleAnalyticsDataAPIToValueInt64Value.model_rebuild()
except NameError:
    pass
try:
    FilterBetweenFilter.model_rebuild()
except NameError:
    pass
try:
    ValueDoubleValue.model_rebuild()
except NameError:
    pass
try:
    ValueInt64Value.model_rebuild()
except NameError:
    pass
